<?php
$places = [
    [
        'name' => '明石',
        'prefecture' => '28',
        'code' => '9',
    ],
    [
        'name' => '尼崎',
        'prefecture' => '28',
        'code' => '6',
    ],
    [
        'name' => '神戸',
        'prefecture' => '28',
        'code' => '7',
    ],
    [
        'name' => '苅藻島',
        'prefecture' => '28',
        'code' => '8',
    ],
    [
        'name' => '由良',
        'prefecture' => '28',
        'code' => '3',
    ],
    [
        'name' => '岩屋',
        'prefecture' => '28',
        'code' => '10',
    ],
    [
        'name' => '高砂',
        'prefecture' => '28',
        'code' => '16',
    ],
    [
        'name' => '飾磨',
        'prefecture' => '28',
        'code' => '17',
    ],
    [
        'name' => '広畑',
        'prefecture' => '28',
        'code' => '18',
    ],
    [
        'name' => '洲本',
        'prefecture' => '28',
        'code' => '4',
    ],
    [
        'name' => '香住',
        'prefecture' => '28',
        'code' => '21',
    ],
    [
        'name' => '米子',
        'prefecture' => '31',
        'code' => '1',
    ],
    [
        'name' => '加賀',
        'prefecture' => '32',
        'code' => '8',
    ],
    [
        'name' => '七類',
        'prefecture' => '32',
        'code' => '9',
    ],
    [
        'name' => '大多府島',
        'prefecture' => '33',
        'code' => '2',
    ],
    [
        'name' => '牛窓',
        'prefecture' => '33',
        'code' => '3',
    ],
    [
        'name' => '小串',
        'prefecture' => '33',
        'code' => '5',
    ],
    [
        'name' => '宇野',
        'prefecture' => '33',
        'code' => '6',
    ],
    [
        'name' => '下津井',
        'prefecture' => '33',
        'code' => '7',
    ],
    [
        'name' => '与島',
        'prefecture' => '37',
        'code' => '12',
    ],
    [
        'name' => '男木島',
        'prefecture' => '37',
        'code' => '7',
    ],
];

$all_places = array(
    array('id' => '1', 'prefecture_code' => '0', 'port_code' => '1', 'prefecture_name' => '千島列島', 'port_name' => '小泊'),
    array('id' => '2', 'prefecture_code' => '0', 'port_code' => '2', 'prefecture_name' => '千島列島', 'port_name' => '中川湾'),
    array('id' => '3', 'prefecture_code' => '0', 'port_code' => '3', 'prefecture_name' => '千島列島', 'port_name' => '片岡湾'),
    array('id' => '4', 'prefecture_code' => '0', 'port_code' => '4', 'prefecture_name' => '千島列島', 'port_name' => '阿頼度島'),
    array('id' => '5', 'prefecture_code' => '0', 'port_code' => '5', 'prefecture_name' => '千島列島', 'port_name' => '磐城埼'),
    array('id' => '6', 'prefecture_code' => '0', 'port_code' => '6', 'prefecture_name' => '千島列島', 'port_name' => '加熊別湾'),
    array('id' => '7', 'prefecture_code' => '0', 'port_code' => '7', 'prefecture_name' => '千島列島', 'port_name' => '鯨湾'),
    array('id' => '8', 'prefecture_code' => '0', 'port_code' => '8', 'prefecture_name' => '千島列島', 'port_name' => '四岩'),
    array('id' => '9', 'prefecture_code' => '0', 'port_code' => '9', 'prefecture_name' => '千島列島', 'port_name' => '乙前湾'),
    array('id' => '10', 'prefecture_code' => '0', 'port_code' => '10', 'prefecture_name' => '千島列島', 'port_name' => '樺里埼'),
    array('id' => '11', 'prefecture_code' => '0', 'port_code' => '11', 'prefecture_name' => '千島列島', 'port_name' => '潮見浦'),
    array('id' => '12', 'prefecture_code' => '0', 'port_code' => '12', 'prefecture_name' => '千島列島', 'port_name' => '黒石湾'),
    array('id' => '13', 'prefecture_code' => '0', 'port_code' => '13', 'prefecture_name' => '千島列島', 'port_name' => '春牟古丹島'),
    array('id' => '14', 'prefecture_code' => '0', 'port_code' => '14', 'prefecture_name' => '千島列島', 'port_name' => '乙女湾'),
    array('id' => '15', 'prefecture_code' => '0', 'port_code' => '15', 'prefecture_name' => '千島列島', 'port_name' => '東浦'),
    array('id' => '16', 'prefecture_code' => '0', 'port_code' => '16', 'prefecture_name' => '千島列島', 'port_name' => '松輪島'),
    array('id' => '17', 'prefecture_code' => '0', 'port_code' => '17', 'prefecture_name' => '千島列島', 'port_name' => '宇志知島'),
    array('id' => '18', 'prefecture_code' => '0', 'port_code' => '18', 'prefecture_name' => '千島列島', 'port_name' => '武魯頓湾'),
    array('id' => '19', 'prefecture_code' => '0', 'port_code' => '19', 'prefecture_name' => '千島列島', 'port_name' => '新知湾'),
    array('id' => '20', 'prefecture_code' => '0', 'port_code' => '20', 'prefecture_name' => '千島列島', 'port_name' => '沙湾'),
    array('id' => '21', 'prefecture_code' => '0', 'port_code' => '21', 'prefecture_name' => '千島列島', 'port_name' => '鐘湾'),
    array('id' => '22', 'prefecture_code' => '0', 'port_code' => '22', 'prefecture_name' => '千島列島', 'port_name' => '床丹島'),
    array('id' => '23', 'prefecture_code' => '0', 'port_code' => '23', 'prefecture_name' => '千島列島', 'port_name' => '吉野浜'),
    array('id' => '24', 'prefecture_code' => '0', 'port_code' => '24', 'prefecture_name' => '千島列島', 'port_name' => '伽藍埼'),
    array('id' => '25', 'prefecture_code' => '1', 'port_code' => '1', 'prefecture_name' => '北海道', 'port_name' => '蘂取'),
    array('id' => '26', 'prefecture_code' => '1', 'port_code' => '2', 'prefecture_name' => '北海道', 'port_name' => '紗万部'),
    array('id' => '27', 'prefecture_code' => '1', 'port_code' => '3', 'prefecture_name' => '北海道', 'port_name' => '内岡'),
    array('id' => '28', 'prefecture_code' => '1', 'port_code' => '4', 'prefecture_name' => '北海道', 'port_name' => '内保湾'),
    array('id' => '29', 'prefecture_code' => '1', 'port_code' => '5', 'prefecture_name' => '北海道', 'port_name' => '茂世路湾'),
    array('id' => '30', 'prefecture_code' => '1', 'port_code' => '6', 'prefecture_name' => '北海道', 'port_name' => '単冠湾'),
    array('id' => '31', 'prefecture_code' => '1', 'port_code' => '7', 'prefecture_name' => '北海道', 'port_name' => '入里節'),
    array('id' => '32', 'prefecture_code' => '1', 'port_code' => '8', 'prefecture_name' => '北海道', 'port_name' => 'ニキシヨロ'),
    array('id' => '33', 'prefecture_code' => '1', 'port_code' => '9', 'prefecture_name' => '北海道', 'port_name' => '古釜府湾'),
    array('id' => '34', 'prefecture_code' => '1', 'port_code' => '10', 'prefecture_name' => '北海道', 'port_name' => '泊湾'),
    array('id' => '35', 'prefecture_code' => '1', 'port_code' => '11', 'prefecture_name' => '北海道', 'port_name' => '水晶島'),
    array('id' => '36', 'prefecture_code' => '1', 'port_code' => '12', 'prefecture_name' => '北海道', 'port_name' => '多楽島'),
    array('id' => '37', 'prefecture_code' => '1', 'port_code' => '13', 'prefecture_name' => '北海道', 'port_name' => '斜古丹'),
    array('id' => '38', 'prefecture_code' => '1', 'port_code' => '14', 'prefecture_name' => '北海道', 'port_name' => '根室'),
    array('id' => '39', 'prefecture_code' => '1', 'port_code' => '15', 'prefecture_name' => '北海道', 'port_name' => '尾岱沼'),
    array('id' => '40', 'prefecture_code' => '1', 'port_code' => '16', 'prefecture_name' => '北海道', 'port_name' => '羅臼'),
    array('id' => '41', 'prefecture_code' => '1', 'port_code' => '17', 'prefecture_name' => '北海道', 'port_name' => 'コイセボイ'),
    array('id' => '42', 'prefecture_code' => '1', 'port_code' => '18', 'prefecture_name' => '北海道', 'port_name' => '網走'),
    array('id' => '43', 'prefecture_code' => '1', 'port_code' => '19', 'prefecture_name' => '北海道', 'port_name' => '紋別'),
    array('id' => '44', 'prefecture_code' => '1', 'port_code' => '20', 'prefecture_name' => '北海道', 'port_name' => '雄武'),
    array('id' => '45', 'prefecture_code' => '1', 'port_code' => '21', 'prefecture_name' => '北海道', 'port_name' => '枝幸'),
    array('id' => '46', 'prefecture_code' => '1', 'port_code' => '22', 'prefecture_name' => '北海道', 'port_name' => '浜鬼志別'),
    array('id' => '47', 'prefecture_code' => '1', 'port_code' => '23', 'prefecture_name' => '北海道', 'port_name' => '宗谷岬'),
    array('id' => '48', 'prefecture_code' => '1', 'port_code' => '24', 'prefecture_name' => '北海道', 'port_name' => '稚内'),
    array('id' => '49', 'prefecture_code' => '1', 'port_code' => '25', 'prefecture_name' => '北海道', 'port_name' => '抜海'),
    array('id' => '50', 'prefecture_code' => '1', 'port_code' => '26', 'prefecture_name' => '北海道', 'port_name' => '鴛泊'),
    array('id' => '51', 'prefecture_code' => '1', 'port_code' => '27', 'prefecture_name' => '北海道', 'port_name' => '沓形'),
    array('id' => '52', 'prefecture_code' => '1', 'port_code' => '28', 'prefecture_name' => '北海道', 'port_name' => '船泊'),
    array('id' => '53', 'prefecture_code' => '1', 'port_code' => '29', 'prefecture_name' => '北海道', 'port_name' => '苫前'),
    array('id' => '54', 'prefecture_code' => '1', 'port_code' => '30', 'prefecture_name' => '北海道', 'port_name' => '留萌'),
    array('id' => '55', 'prefecture_code' => '1', 'port_code' => '31', 'prefecture_name' => '北海道', 'port_name' => '浜益'),
    array('id' => '56', 'prefecture_code' => '1', 'port_code' => '32', 'prefecture_name' => '北海道', 'port_name' => '小樽'),
    array('id' => '57', 'prefecture_code' => '1', 'port_code' => '33', 'prefecture_name' => '北海道', 'port_name' => '忍路'),
    array('id' => '58', 'prefecture_code' => '1', 'port_code' => '34', 'prefecture_name' => '北海道', 'port_name' => '神威岬'),
    array('id' => '59', 'prefecture_code' => '1', 'port_code' => '35', 'prefecture_name' => '北海道', 'port_name' => '岩内'),
    array('id' => '60', 'prefecture_code' => '1', 'port_code' => '36', 'prefecture_name' => '北海道', 'port_name' => '寿都'),
    array('id' => '61', 'prefecture_code' => '1', 'port_code' => '37', 'prefecture_name' => '北海道', 'port_name' => '瀬棚'),
    array('id' => '62', 'prefecture_code' => '1', 'port_code' => '38', 'prefecture_name' => '北海道', 'port_name' => '奥尻'),
    array('id' => '63', 'prefecture_code' => '1', 'port_code' => '39', 'prefecture_name' => '北海道', 'port_name' => '青苗'),
    array('id' => '64', 'prefecture_code' => '1', 'port_code' => '40', 'prefecture_name' => '北海道', 'port_name' => '江差'),
    array('id' => '65', 'prefecture_code' => '1', 'port_code' => '41', 'prefecture_name' => '北海道', 'port_name' => '清部'),
    array('id' => '66', 'prefecture_code' => '1', 'port_code' => '42', 'prefecture_name' => '北海道', 'port_name' => '松前'),
    array('id' => '67', 'prefecture_code' => '1', 'port_code' => '43', 'prefecture_name' => '北海道', 'port_name' => '吉岡'),
    array('id' => '68', 'prefecture_code' => '1', 'port_code' => '44', 'prefecture_name' => '北海道', 'port_name' => '湧元'),
    array('id' => '69', 'prefecture_code' => '1', 'port_code' => '45', 'prefecture_name' => '北海道', 'port_name' => '函館'),
    array('id' => '70', 'prefecture_code' => '1', 'port_code' => '46', 'prefecture_name' => '北海道', 'port_name' => '汐首岬'),
    array('id' => '71', 'prefecture_code' => '1', 'port_code' => '47', 'prefecture_name' => '北海道', 'port_name' => '戸井'),
    array('id' => '72', 'prefecture_code' => '1', 'port_code' => '48', 'prefecture_name' => '北海道', 'port_name' => '古武井'),
    array('id' => '73', 'prefecture_code' => '1', 'port_code' => '49', 'prefecture_name' => '北海道', 'port_name' => '臼尻'),
    array('id' => '74', 'prefecture_code' => '1', 'port_code' => '50', 'prefecture_name' => '北海道', 'port_name' => '森'),
    array('id' => '75', 'prefecture_code' => '1', 'port_code' => '51', 'prefecture_name' => '北海道', 'port_name' => '有珠湾'),
    array('id' => '76', 'prefecture_code' => '1', 'port_code' => '52', 'prefecture_name' => '北海道', 'port_name' => '室蘭'),
    array('id' => '77', 'prefecture_code' => '1', 'port_code' => '53', 'prefecture_name' => '北海道', 'port_name' => '苫小牧'),
    array('id' => '78', 'prefecture_code' => '1', 'port_code' => '54', 'prefecture_name' => '北海道', 'port_name' => '東静内'),
    array('id' => '79', 'prefecture_code' => '1', 'port_code' => '55', 'prefecture_name' => '北海道', 'port_name' => '三石'),
    array('id' => '80', 'prefecture_code' => '1', 'port_code' => '56', 'prefecture_name' => '北海道', 'port_name' => '浦河'),
    array('id' => '81', 'prefecture_code' => '1', 'port_code' => '57', 'prefecture_name' => '北海道', 'port_name' => 'えりも'),
    array('id' => '82', 'prefecture_code' => '1', 'port_code' => '58', 'prefecture_name' => '北海道', 'port_name' => '歌露'),
    array('id' => '83', 'prefecture_code' => '1', 'port_code' => '59', 'prefecture_name' => '北海道', 'port_name' => '襟裳岬'),
    array('id' => '84', 'prefecture_code' => '1', 'port_code' => '60', 'prefecture_name' => '北海道', 'port_name' => '庶野'),
    array('id' => '85', 'prefecture_code' => '1', 'port_code' => '61', 'prefecture_name' => '北海道', 'port_name' => 'ルベシベツ'),
    array('id' => '86', 'prefecture_code' => '1', 'port_code' => '62', 'prefecture_name' => '北海道', 'port_name' => '音調津'),
    array('id' => '87', 'prefecture_code' => '1', 'port_code' => '63', 'prefecture_name' => '北海道', 'port_name' => '十勝'),
    array('id' => '88', 'prefecture_code' => '1', 'port_code' => '64', 'prefecture_name' => '北海道', 'port_name' => '釧路'),
    array('id' => '89', 'prefecture_code' => '1', 'port_code' => '65', 'prefecture_name' => '北海道', 'port_name' => '厚岸'),
    array('id' => '90', 'prefecture_code' => '1', 'port_code' => '66', 'prefecture_name' => '北海道', 'port_name' => '厚岸湖'),
    array('id' => '91', 'prefecture_code' => '1', 'port_code' => '67', 'prefecture_name' => '北海道', 'port_name' => '霧多布'),
    array('id' => '92', 'prefecture_code' => '1', 'port_code' => '68', 'prefecture_name' => '北海道', 'port_name' => '落石'),
    array('id' => '93', 'prefecture_code' => '1', 'port_code' => '69', 'prefecture_name' => '北海道', 'port_name' => '花咲'),
    array('id' => '94', 'prefecture_code' => '1', 'port_code' => '70', 'prefecture_name' => '北海道', 'port_name' => '香深'),
    array('id' => '95', 'prefecture_code' => '1', 'port_code' => '71', 'prefecture_name' => '北海道', 'port_name' => '常呂'),
    array('id' => '96', 'prefecture_code' => '1', 'port_code' => '72', 'prefecture_name' => '北海道', 'port_name' => '湧別'),
    array('id' => '97', 'prefecture_code' => '1', 'port_code' => '73', 'prefecture_name' => '北海道', 'port_name' => '利尻'),
    array('id' => '98', 'prefecture_code' => '2', 'port_code' => '1', 'prefecture_name' => '青森県', 'port_name' => '竜飛埼'),
    array('id' => '99', 'prefecture_code' => '2', 'port_code' => '2', 'prefecture_name' => '青森県', 'port_name' => '三厩'),
    array('id' => '100', 'prefecture_code' => '2', 'port_code' => '3', 'prefecture_name' => '青森県', 'port_name' => '袰月'),
    array('id' => '101', 'prefecture_code' => '2', 'port_code' => '4', 'prefecture_name' => '青森県', 'port_name' => '青森'),
    array('id' => '102', 'prefecture_code' => '2', 'port_code' => '5', 'prefecture_name' => '青森県', 'port_name' => '茂浦'),
    array('id' => '103', 'prefecture_code' => '2', 'port_code' => '6', 'prefecture_name' => '青森県', 'port_name' => '小湊'),
    array('id' => '104', 'prefecture_code' => '2', 'port_code' => '7', 'prefecture_name' => '青森県', 'port_name' => '野辺地'),
    array('id' => '105', 'prefecture_code' => '2', 'port_code' => '8', 'prefecture_name' => '青森県', 'port_name' => '大湊'),
    array('id' => '106', 'prefecture_code' => '2', 'port_code' => '9', 'prefecture_name' => '青森県', 'port_name' => '大間'),
    array('id' => '107', 'prefecture_code' => '2', 'port_code' => '10', 'prefecture_name' => '青森県', 'port_name' => '大畑'),
    array('id' => '108', 'prefecture_code' => '2', 'port_code' => '11', 'prefecture_name' => '青森県', 'port_name' => '尻屋岬'),
    array('id' => '109', 'prefecture_code' => '2', 'port_code' => '12', 'prefecture_name' => '青森県', 'port_name' => '尻屋'),
    array('id' => '110', 'prefecture_code' => '2', 'port_code' => '13', 'prefecture_name' => '青森県', 'port_name' => '白糠'),
    array('id' => '111', 'prefecture_code' => '2', 'port_code' => '14', 'prefecture_name' => '青森県', 'port_name' => '泊'),
    array('id' => '112', 'prefecture_code' => '2', 'port_code' => '15', 'prefecture_name' => '青森県', 'port_name' => '八戸'),
    array('id' => '113', 'prefecture_code' => '2', 'port_code' => '16', 'prefecture_name' => '青森県', 'port_name' => '岩崎'),
    array('id' => '114', 'prefecture_code' => '2', 'port_code' => '17', 'prefecture_name' => '青森県', 'port_name' => '深浦'),
    array('id' => '115', 'prefecture_code' => '2', 'port_code' => '18', 'prefecture_name' => '青森県', 'port_name' => '鯵ヶ沢'),
    array('id' => '116', 'prefecture_code' => '2', 'port_code' => '19', 'prefecture_name' => '青森県', 'port_name' => '小泊'),
    array('id' => '117', 'prefecture_code' => '2', 'port_code' => '20', 'prefecture_name' => '青森県', 'port_name' => '関根浜'),
    array('id' => '118', 'prefecture_code' => '2', 'port_code' => '21', 'prefecture_name' => '青森県', 'port_name' => '浅虫'),
    array('id' => '119', 'prefecture_code' => '2', 'port_code' => '22', 'prefecture_name' => '青森県', 'port_name' => '竜飛'),
    array('id' => '120', 'prefecture_code' => '3', 'port_code' => '1', 'prefecture_name' => '岩手県', 'port_name' => '久慈'),
    array('id' => '121', 'prefecture_code' => '3', 'port_code' => '2', 'prefecture_name' => '岩手県', 'port_name' => '宮古'),
    array('id' => '122', 'prefecture_code' => '3', 'port_code' => '3', 'prefecture_name' => '岩手県', 'port_name' => '山田'),
    array('id' => '123', 'prefecture_code' => '3', 'port_code' => '4', 'prefecture_name' => '岩手県', 'port_name' => '釜石'),
    array('id' => '124', 'prefecture_code' => '3', 'port_code' => '5', 'prefecture_name' => '岩手県', 'port_name' => '大船渡'),
    array('id' => '125', 'prefecture_code' => '3', 'port_code' => '6', 'prefecture_name' => '岩手県', 'port_name' => '八木'),
    array('id' => '126', 'prefecture_code' => '3', 'port_code' => '7', 'prefecture_name' => '岩手県', 'port_name' => '茂師'),
    array('id' => '127', 'prefecture_code' => '4', 'port_code' => '1', 'prefecture_name' => '秋田県', 'port_name' => '気仙沼'),
    array('id' => '128', 'prefecture_code' => '4', 'port_code' => '2', 'prefecture_name' => '秋田県', 'port_name' => '船越湾'),
    array('id' => '129', 'prefecture_code' => '4', 'port_code' => '3', 'prefecture_name' => '秋田県', 'port_name' => '女川'),
    array('id' => '130', 'prefecture_code' => '4', 'port_code' => '4', 'prefecture_name' => '秋田県', 'port_name' => '鮎川'),
    array('id' => '131', 'prefecture_code' => '4', 'port_code' => '5', 'prefecture_name' => '秋田県', 'port_name' => '荻浜'),
    array('id' => '132', 'prefecture_code' => '4', 'port_code' => '6', 'prefecture_name' => '秋田県', 'port_name' => '石巻'),
    array('id' => '133', 'prefecture_code' => '4', 'port_code' => '7', 'prefecture_name' => '秋田県', 'port_name' => '野蒜湾'),
    array('id' => '134', 'prefecture_code' => '4', 'port_code' => '8', 'prefecture_name' => '秋田県', 'port_name' => '石浜'),
    array('id' => '135', 'prefecture_code' => '4', 'port_code' => '9', 'prefecture_name' => '秋田県', 'port_name' => '港橋'),
    array('id' => '136', 'prefecture_code' => '4', 'port_code' => '10', 'prefecture_name' => '秋田県', 'port_name' => '花淵浜'),
    array('id' => '137', 'prefecture_code' => '4', 'port_code' => '11', 'prefecture_name' => '秋田県', 'port_name' => '仙台'),
    array('id' => '138', 'prefecture_code' => '4', 'port_code' => '12', 'prefecture_name' => '秋田県', 'port_name' => '閖上'),
    array('id' => '139', 'prefecture_code' => '4', 'port_code' => '13', 'prefecture_name' => '秋田県', 'port_name' => '志津川'),
    array('id' => '140', 'prefecture_code' => '5', 'port_code' => '1', 'prefecture_name' => '宮城県', 'port_name' => '金浦'),
    array('id' => '141', 'prefecture_code' => '5', 'port_code' => '2', 'prefecture_name' => '宮城県', 'port_name' => '秋田'),
    array('id' => '142', 'prefecture_code' => '5', 'port_code' => '3', 'prefecture_name' => '宮城県', 'port_name' => '船川'),
    array('id' => '143', 'prefecture_code' => '5', 'port_code' => '4', 'prefecture_name' => '宮城県', 'port_name' => '能代'),
    array('id' => '144', 'prefecture_code' => '5', 'port_code' => '5', 'prefecture_name' => '宮城県', 'port_name' => '岩館'),
    array('id' => '145', 'prefecture_code' => '5', 'port_code' => '6', 'prefecture_name' => '宮城県', 'port_name' => '男鹿'),
    array('id' => '146', 'prefecture_code' => '6', 'port_code' => '1', 'prefecture_name' => '山形県', 'port_name' => '鼠ヶ関'),
    array('id' => '147', 'prefecture_code' => '6', 'port_code' => '2', 'prefecture_name' => '山形県', 'port_name' => '由良'),
    array('id' => '148', 'prefecture_code' => '6', 'port_code' => '3', 'prefecture_name' => '山形県', 'port_name' => '加茂'),
    array('id' => '149', 'prefecture_code' => '6', 'port_code' => '4', 'prefecture_name' => '山形県', 'port_name' => '酒田'),
    array('id' => '150', 'prefecture_code' => '7', 'port_code' => '1', 'prefecture_name' => '福島県', 'port_name' => '相馬'),
    array('id' => '151', 'prefecture_code' => '7', 'port_code' => '2', 'prefecture_name' => '福島県', 'port_name' => '松川浦'),
    array('id' => '152', 'prefecture_code' => '7', 'port_code' => '3', 'prefecture_name' => '福島県', 'port_name' => '夫沢'),
    array('id' => '153', 'prefecture_code' => '7', 'port_code' => '4', 'prefecture_name' => '福島県', 'port_name' => '富岡'),
    array('id' => '154', 'prefecture_code' => '7', 'port_code' => '5', 'prefecture_name' => '福島県', 'port_name' => '四倉'),
    array('id' => '155', 'prefecture_code' => '7', 'port_code' => '6', 'prefecture_name' => '福島県', 'port_name' => '小名浜'),
    array('id' => '156', 'prefecture_code' => '8', 'port_code' => '1', 'prefecture_name' => '茨城県', 'port_name' => '大津'),
    array('id' => '157', 'prefecture_code' => '8', 'port_code' => '2', 'prefecture_name' => '茨城県', 'port_name' => '日立'),
    array('id' => '158', 'prefecture_code' => '8', 'port_code' => '3', 'prefecture_name' => '茨城県', 'port_name' => '那珂湊'),
    array('id' => '159', 'prefecture_code' => '8', 'port_code' => '4', 'prefecture_name' => '茨城県', 'port_name' => '鹿島'),
    array('id' => '160', 'prefecture_code' => '8', 'port_code' => '5', 'prefecture_name' => '茨城県', 'port_name' => '大洗'),
    array('id' => '161', 'prefecture_code' => '12', 'port_code' => '1', 'prefecture_name' => '千葉県', 'port_name' => '新地'),
    array('id' => '162', 'prefecture_code' => '12', 'port_code' => '2', 'prefecture_name' => '千葉県', 'port_name' => '銚子漁港'),
    array('id' => '163', 'prefecture_code' => '12', 'port_code' => '3', 'prefecture_name' => '千葉県', 'port_name' => '犬吠埼'),
    array('id' => '164', 'prefecture_code' => '12', 'port_code' => '4', 'prefecture_name' => '千葉県', 'port_name' => '名洗'),
    array('id' => '165', 'prefecture_code' => '12', 'port_code' => '5', 'prefecture_name' => '千葉県', 'port_name' => '上総勝浦'),
    array('id' => '166', 'prefecture_code' => '12', 'port_code' => '6', 'prefecture_name' => '千葉県', 'port_name' => '鴨川'),
    array('id' => '167', 'prefecture_code' => '12', 'port_code' => '7', 'prefecture_name' => '千葉県', 'port_name' => '白浜'),
    array('id' => '168', 'prefecture_code' => '12', 'port_code' => '8', 'prefecture_name' => '千葉県', 'port_name' => '布良'),
    array('id' => '169', 'prefecture_code' => '12', 'port_code' => '9', 'prefecture_name' => '千葉県', 'port_name' => '船形'),
    array('id' => '170', 'prefecture_code' => '12', 'port_code' => '10', 'prefecture_name' => '千葉県', 'port_name' => '岩井袋'),
    array('id' => '171', 'prefecture_code' => '12', 'port_code' => '11', 'prefecture_name' => '千葉県', 'port_name' => '第１海堡'),
    array('id' => '172', 'prefecture_code' => '12', 'port_code' => '12', 'prefecture_name' => '千葉県', 'port_name' => '君津'),
    array('id' => '173', 'prefecture_code' => '12', 'port_code' => '13', 'prefecture_name' => '千葉県', 'port_name' => '姉崎'),
    array('id' => '174', 'prefecture_code' => '12', 'port_code' => '14', 'prefecture_name' => '千葉県', 'port_name' => '市原'),
    array('id' => '175', 'prefecture_code' => '12', 'port_code' => '15', 'prefecture_name' => '千葉県', 'port_name' => '寒川'),
    array('id' => '176', 'prefecture_code' => '12', 'port_code' => '16', 'prefecture_name' => '千葉県', 'port_name' => '千葉灯標'),
    array('id' => '177', 'prefecture_code' => '12', 'port_code' => '17', 'prefecture_name' => '千葉県', 'port_name' => '市川'),
    array('id' => '178', 'prefecture_code' => '12', 'port_code' => '18', 'prefecture_name' => '千葉県', 'port_name' => '船橋'),
    array('id' => '179', 'prefecture_code' => '12', 'port_code' => '19', 'prefecture_name' => '千葉県', 'port_name' => '館山'),
    array('id' => '180', 'prefecture_code' => '13', 'port_code' => '1', 'prefecture_name' => '東京都', 'port_name' => '築地'),
    array('id' => '181', 'prefecture_code' => '13', 'port_code' => '2', 'prefecture_name' => '東京都', 'port_name' => '芝浦'),
    array('id' => '182', 'prefecture_code' => '13', 'port_code' => '3', 'prefecture_name' => '東京都', 'port_name' => '羽田'),
    array('id' => '183', 'prefecture_code' => '13', 'port_code' => '4', 'prefecture_name' => '東京都', 'port_name' => '岡田'),
    array('id' => '184', 'prefecture_code' => '13', 'port_code' => '5', 'prefecture_name' => '東京都', 'port_name' => '波浮'),
    array('id' => '185', 'prefecture_code' => '13', 'port_code' => '6', 'prefecture_name' => '東京都', 'port_name' => '式根島'),
    array('id' => '186', 'prefecture_code' => '13', 'port_code' => '7', 'prefecture_name' => '東京都', 'port_name' => '神津島'),
    array('id' => '187', 'prefecture_code' => '13', 'port_code' => '8', 'prefecture_name' => '東京都', 'port_name' => '阿古'),
    array('id' => '188', 'prefecture_code' => '13', 'port_code' => '9', 'prefecture_name' => '東京都', 'port_name' => '神湊'),
    array('id' => '189', 'prefecture_code' => '13', 'port_code' => '10', 'prefecture_name' => '東京都', 'port_name' => '鳥島'),
    array('id' => '190', 'prefecture_code' => '13', 'port_code' => '11', 'prefecture_name' => '東京都', 'port_name' => '二見'),
    array('id' => '191', 'prefecture_code' => '13', 'port_code' => '12', 'prefecture_name' => '東京都', 'port_name' => '沖'),
    array('id' => '192', 'prefecture_code' => '13', 'port_code' => '13', 'prefecture_name' => '東京都', 'port_name' => '西'),
    array('id' => '193', 'prefecture_code' => '13', 'port_code' => '14', 'prefecture_name' => '東京都', 'port_name' => '晴海'),
    array('id' => '194', 'prefecture_code' => '13', 'port_code' => '15', 'prefecture_name' => '東京都', 'port_name' => '八重根'),
    array('id' => '195', 'prefecture_code' => '13', 'port_code' => '16', 'prefecture_name' => '東京都', 'port_name' => '沖ノ鳥島'),
    array('id' => '196', 'prefecture_code' => '14', 'port_code' => '1', 'prefecture_name' => '神奈川県', 'port_name' => '塩浜運河'),
    array('id' => '197', 'prefecture_code' => '14', 'port_code' => '2', 'prefecture_name' => '神奈川県', 'port_name' => '末広'),
    array('id' => '198', 'prefecture_code' => '14', 'port_code' => '3', 'prefecture_name' => '神奈川県', 'port_name' => '新港'),
    array('id' => '199', 'prefecture_code' => '14', 'port_code' => '4', 'prefecture_name' => '神奈川県', 'port_name' => '新山下'),
    array('id' => '200', 'prefecture_code' => '14', 'port_code' => '5', 'prefecture_name' => '神奈川県', 'port_name' => '根岸'),
    array('id' => '201', 'prefecture_code' => '14', 'port_code' => '6', 'prefecture_name' => '神奈川県', 'port_name' => '長浦'),
    array('id' => '202', 'prefecture_code' => '14', 'port_code' => '7', 'prefecture_name' => '神奈川県', 'port_name' => '横須賀'),
    array('id' => '203', 'prefecture_code' => '14', 'port_code' => '8', 'prefecture_name' => '神奈川県', 'port_name' => '走水'),
    array('id' => '204', 'prefecture_code' => '14', 'port_code' => '9', 'prefecture_name' => '神奈川県', 'port_name' => '浦賀'),
    array('id' => '205', 'prefecture_code' => '14', 'port_code' => '10', 'prefecture_name' => '神奈川県', 'port_name' => '久里浜'),
    array('id' => '206', 'prefecture_code' => '14', 'port_code' => '11', 'prefecture_name' => '神奈川県', 'port_name' => '金田湾'),
    array('id' => '207', 'prefecture_code' => '14', 'port_code' => '12', 'prefecture_name' => '神奈川県', 'port_name' => '間口'),
    array('id' => '208', 'prefecture_code' => '14', 'port_code' => '13', 'prefecture_name' => '神奈川県', 'port_name' => '城ヶ島'),
    array('id' => '209', 'prefecture_code' => '14', 'port_code' => '14', 'prefecture_name' => '神奈川県', 'port_name' => '向ヶ崎'),
    array('id' => '210', 'prefecture_code' => '14', 'port_code' => '15', 'prefecture_name' => '神奈川県', 'port_name' => '諸磯'),
    array('id' => '211', 'prefecture_code' => '14', 'port_code' => '16', 'prefecture_name' => '神奈川県', 'port_name' => '油壷'),
    array('id' => '212', 'prefecture_code' => '14', 'port_code' => '17', 'prefecture_name' => '神奈川県', 'port_name' => '小田和湾'),
    array('id' => '213', 'prefecture_code' => '14', 'port_code' => '18', 'prefecture_name' => '神奈川県', 'port_name' => '新宿湾'),
    array('id' => '214', 'prefecture_code' => '14', 'port_code' => '19', 'prefecture_name' => '神奈川県', 'port_name' => '江ノ島'),
    array('id' => '215', 'prefecture_code' => '14', 'port_code' => '20', 'prefecture_name' => '神奈川県', 'port_name' => '真鶴'),
    array('id' => '216', 'prefecture_code' => '15', 'port_code' => '1', 'prefecture_name' => '新潟県', 'port_name' => '能生'),
    array('id' => '217', 'prefecture_code' => '15', 'port_code' => '2', 'prefecture_name' => '新潟県', 'port_name' => '直江津'),
    array('id' => '218', 'prefecture_code' => '15', 'port_code' => '3', 'prefecture_name' => '新潟県', 'port_name' => '柏崎'),
    array('id' => '219', 'prefecture_code' => '15', 'port_code' => '4', 'prefecture_name' => '新潟県', 'port_name' => '出雲崎'),
    array('id' => '220', 'prefecture_code' => '15', 'port_code' => '5', 'prefecture_name' => '新潟県', 'port_name' => '寺泊'),
    array('id' => '221', 'prefecture_code' => '15', 'port_code' => '6', 'prefecture_name' => '新潟県', 'port_name' => '新潟西港'),
    array('id' => '222', 'prefecture_code' => '15', 'port_code' => '7', 'prefecture_name' => '新潟県', 'port_name' => '二見'),
    array('id' => '223', 'prefecture_code' => '15', 'port_code' => '8', 'prefecture_name' => '新潟県', 'port_name' => '小木'),
    array('id' => '224', 'prefecture_code' => '15', 'port_code' => '9', 'prefecture_name' => '新潟県', 'port_name' => '両津'),
    array('id' => '225', 'prefecture_code' => '15', 'port_code' => '10', 'prefecture_name' => '新潟県', 'port_name' => '鷲崎'),
    array('id' => '226', 'prefecture_code' => '15', 'port_code' => '11', 'prefecture_name' => '新潟県', 'port_name' => '岩船'),
    array('id' => '227', 'prefecture_code' => '15', 'port_code' => '12', 'prefecture_name' => '新潟県', 'port_name' => '粟島'),
    array('id' => '228', 'prefecture_code' => '15', 'port_code' => '13', 'prefecture_name' => '新潟県', 'port_name' => '新潟東港'),
    array('id' => '229', 'prefecture_code' => '16', 'port_code' => '1', 'prefecture_name' => '富山県', 'port_name' => '阿尾'),
    array('id' => '230', 'prefecture_code' => '16', 'port_code' => '2', 'prefecture_name' => '富山県', 'port_name' => '伏木'),
    array('id' => '231', 'prefecture_code' => '16', 'port_code' => '3', 'prefecture_name' => '富山県', 'port_name' => '富山'),
    array('id' => '232', 'prefecture_code' => '16', 'port_code' => '4', 'prefecture_name' => '富山県', 'port_name' => '生地'),
    array('id' => '233', 'prefecture_code' => '16', 'port_code' => '5', 'prefecture_name' => '富山県', 'port_name' => '宮崎'),
    array('id' => '234', 'prefecture_code' => '17', 'port_code' => '1', 'prefecture_name' => '石川県', 'port_name' => '金沢'),
    array('id' => '235', 'prefecture_code' => '17', 'port_code' => '2', 'prefecture_name' => '石川県', 'port_name' => '滝'),
    array('id' => '236', 'prefecture_code' => '17', 'port_code' => '3', 'prefecture_name' => '石川県', 'port_name' => '寺家'),
    array('id' => '237', 'prefecture_code' => '17', 'port_code' => '4', 'prefecture_name' => '石川県', 'port_name' => '輪島'),
    array('id' => '238', 'prefecture_code' => '17', 'port_code' => '5', 'prefecture_name' => '石川県', 'port_name' => '松波'),
    array('id' => '239', 'prefecture_code' => '17', 'port_code' => '6', 'prefecture_name' => '石川県', 'port_name' => '曾良'),
    array('id' => '240', 'prefecture_code' => '17', 'port_code' => '7', 'prefecture_name' => '石川県', 'port_name' => '中居入'),
    array('id' => '241', 'prefecture_code' => '17', 'port_code' => '8', 'prefecture_name' => '石川県', 'port_name' => '七尾'),
    array('id' => '242', 'prefecture_code' => '17', 'port_code' => '9', 'prefecture_name' => '石川県', 'port_name' => '穴水'),
    array('id' => '243', 'prefecture_code' => '18', 'port_code' => '1', 'prefecture_name' => '福井県', 'port_name' => '内浦湾'),
    array('id' => '244', 'prefecture_code' => '18', 'port_code' => '2', 'prefecture_name' => '福井県', 'port_name' => '和田'),
    array('id' => '245', 'prefecture_code' => '18', 'port_code' => '3', 'prefecture_name' => '福井県', 'port_name' => '小浜'),
    array('id' => '246', 'prefecture_code' => '18', 'port_code' => '4', 'prefecture_name' => '福井県', 'port_name' => '丹生'),
    array('id' => '247', 'prefecture_code' => '18', 'port_code' => '5', 'prefecture_name' => '福井県', 'port_name' => '敦賀'),
    array('id' => '248', 'prefecture_code' => '18', 'port_code' => '6', 'prefecture_name' => '福井県', 'port_name' => '福井'),
    array('id' => '249', 'prefecture_code' => '18', 'port_code' => '7', 'prefecture_name' => '福井県', 'port_name' => '三国'),
    array('id' => '250', 'prefecture_code' => '22', 'port_code' => '1', 'prefecture_name' => '静岡県', 'port_name' => '網代'),
    array('id' => '251', 'prefecture_code' => '22', 'port_code' => '2', 'prefecture_name' => '静岡県', 'port_name' => '伊東'),
    array('id' => '252', 'prefecture_code' => '22', 'port_code' => '3', 'prefecture_name' => '静岡県', 'port_name' => '川奈'),
    array('id' => '253', 'prefecture_code' => '22', 'port_code' => '4', 'prefecture_name' => '静岡県', 'port_name' => '白浜'),
    array('id' => '254', 'prefecture_code' => '22', 'port_code' => '5', 'prefecture_name' => '静岡県', 'port_name' => '下田'),
    array('id' => '255', 'prefecture_code' => '22', 'port_code' => '6', 'prefecture_name' => '静岡県', 'port_name' => '南伊豆'),
    array('id' => '256', 'prefecture_code' => '22', 'port_code' => '7', 'prefecture_name' => '静岡県', 'port_name' => '妻良子浦'),
    array('id' => '257', 'prefecture_code' => '22', 'port_code' => '8', 'prefecture_name' => '静岡県', 'port_name' => '田子'),
    array('id' => '258', 'prefecture_code' => '22', 'port_code' => '9', 'prefecture_name' => '静岡県', 'port_name' => '宇久須'),
    array('id' => '259', 'prefecture_code' => '22', 'port_code' => '10', 'prefecture_name' => '静岡県', 'port_name' => '三津'),
    array('id' => '260', 'prefecture_code' => '22', 'port_code' => '11', 'prefecture_name' => '静岡県', 'port_name' => '田子の浦'),
    array('id' => '261', 'prefecture_code' => '22', 'port_code' => '12', 'prefecture_name' => '静岡県', 'port_name' => '興津'),
    array('id' => '262', 'prefecture_code' => '22', 'port_code' => '13', 'prefecture_name' => '静岡県', 'port_name' => '清水'),
    array('id' => '263', 'prefecture_code' => '22', 'port_code' => '14', 'prefecture_name' => '静岡県', 'port_name' => '三保'),
    array('id' => '264', 'prefecture_code' => '22', 'port_code' => '15', 'prefecture_name' => '静岡県', 'port_name' => '焼津'),
    array('id' => '265', 'prefecture_code' => '22', 'port_code' => '16', 'prefecture_name' => '静岡県', 'port_name' => '相良'),
    array('id' => '266', 'prefecture_code' => '22', 'port_code' => '17', 'prefecture_name' => '静岡県', 'port_name' => '御前崎'),
    array('id' => '267', 'prefecture_code' => '22', 'port_code' => '18', 'prefecture_name' => '静岡県', 'port_name' => '舞阪'),
    array('id' => '268', 'prefecture_code' => '22', 'port_code' => '19', 'prefecture_name' => '静岡県', 'port_name' => '熱海'),
    array('id' => '269', 'prefecture_code' => '23', 'port_code' => '1', 'prefecture_name' => '愛知県', 'port_name' => '伊良湖'),
    array('id' => '270', 'prefecture_code' => '23', 'port_code' => '2', 'prefecture_name' => '愛知県', 'port_name' => '神島'),
    array('id' => '271', 'prefecture_code' => '23', 'port_code' => '3', 'prefecture_name' => '愛知県', 'port_name' => '篠島'),
    array('id' => '272', 'prefecture_code' => '23', 'port_code' => '4', 'prefecture_name' => '愛知県', 'port_name' => '佐久島'),
    array('id' => '273', 'prefecture_code' => '23', 'port_code' => '5', 'prefecture_name' => '愛知県', 'port_name' => '立馬埼'),
    array('id' => '274', 'prefecture_code' => '23', 'port_code' => '6', 'prefecture_name' => '愛知県', 'port_name' => '福江'),
    array('id' => '275', 'prefecture_code' => '23', 'port_code' => '7', 'prefecture_name' => '愛知県', 'port_name' => '豊橋'),
    array('id' => '276', 'prefecture_code' => '23', 'port_code' => '8', 'prefecture_name' => '愛知県', 'port_name' => '三谷'),
    array('id' => '277', 'prefecture_code' => '23', 'port_code' => '9', 'prefecture_name' => '愛知県', 'port_name' => '蒲郡'),
    array('id' => '278', 'prefecture_code' => '23', 'port_code' => '10', 'prefecture_name' => '愛知県', 'port_name' => '形原'),
    array('id' => '279', 'prefecture_code' => '23', 'port_code' => '11', 'prefecture_name' => '愛知県', 'port_name' => '洲崎'),
    array('id' => '280', 'prefecture_code' => '23', 'port_code' => '12', 'prefecture_name' => '愛知県', 'port_name' => '寺津'),
    array('id' => '281', 'prefecture_code' => '23', 'port_code' => '13', 'prefecture_name' => '愛知県', 'port_name' => '武豊'),
    array('id' => '282', 'prefecture_code' => '23', 'port_code' => '14', 'prefecture_name' => '愛知県', 'port_name' => '師崎'),
    array('id' => '283', 'prefecture_code' => '23', 'port_code' => '15', 'prefecture_name' => '愛知県', 'port_name' => '常滑'),
    array('id' => '284', 'prefecture_code' => '23', 'port_code' => '16', 'prefecture_name' => '愛知県', 'port_name' => '鬼崎'),
    array('id' => '285', 'prefecture_code' => '23', 'port_code' => '17', 'prefecture_name' => '愛知県', 'port_name' => '名古屋'),
    array('id' => '286', 'prefecture_code' => '23', 'port_code' => '18', 'prefecture_name' => '愛知県', 'port_name' => '赤羽根'),
    array('id' => '287', 'prefecture_code' => '24', 'port_code' => '1', 'prefecture_name' => '三重県', 'port_name' => '四日市'),
    array('id' => '288', 'prefecture_code' => '24', 'port_code' => '2', 'prefecture_name' => '三重県', 'port_name' => '津'),
    array('id' => '289', 'prefecture_code' => '24', 'port_code' => '3', 'prefecture_name' => '三重県', 'port_name' => '松阪'),
    array('id' => '290', 'prefecture_code' => '24', 'port_code' => '4', 'prefecture_name' => '三重県', 'port_name' => '宇治山田'),
    array('id' => '291', 'prefecture_code' => '24', 'port_code' => '5', 'prefecture_name' => '三重県', 'port_name' => '鳥羽'),
    array('id' => '292', 'prefecture_code' => '24', 'port_code' => '6', 'prefecture_name' => '三重県', 'port_name' => '的矢'),
    array('id' => '293', 'prefecture_code' => '24', 'port_code' => '7', 'prefecture_name' => '三重県', 'port_name' => '浜島'),
    array('id' => '294', 'prefecture_code' => '24', 'port_code' => '8', 'prefecture_name' => '三重県', 'port_name' => '五ヶ所'),
    array('id' => '295', 'prefecture_code' => '24', 'port_code' => '9', 'prefecture_name' => '三重県', 'port_name' => '吉津'),
    array('id' => '296', 'prefecture_code' => '24', 'port_code' => '10', 'prefecture_name' => '三重県', 'port_name' => '長島'),
    array('id' => '297', 'prefecture_code' => '24', 'port_code' => '11', 'prefecture_name' => '三重県', 'port_name' => '尾鷲'),
    array('id' => '298', 'prefecture_code' => '24', 'port_code' => '12', 'prefecture_name' => '三重県', 'port_name' => '古江'),
    array('id' => '299', 'prefecture_code' => '24', 'port_code' => '13', 'prefecture_name' => '三重県', 'port_name' => '二木島'),
    array('id' => '300', 'prefecture_code' => '24', 'port_code' => '14', 'prefecture_name' => '三重県', 'port_name' => '鵜殿'),
    array('id' => '301', 'prefecture_code' => '24', 'port_code' => '15', 'prefecture_name' => '三重県', 'port_name' => '錦'),
    array('id' => '302', 'prefecture_code' => '26', 'port_code' => '1', 'prefecture_name' => '京都府', 'port_name' => '伊根'),
    array('id' => '303', 'prefecture_code' => '26', 'port_code' => '2', 'prefecture_name' => '京都府', 'port_name' => '島埼'),
    array('id' => '304', 'prefecture_code' => '26', 'port_code' => '3', 'prefecture_name' => '京都府', 'port_name' => '獅子崎'),
    array('id' => '305', 'prefecture_code' => '26', 'port_code' => '4', 'prefecture_name' => '京都府', 'port_name' => '田井'),
    array('id' => '306', 'prefecture_code' => '26', 'port_code' => '5', 'prefecture_name' => '京都府', 'port_name' => '舞鶴東港'),
    array('id' => '307', 'prefecture_code' => '26', 'port_code' => '6', 'prefecture_name' => '京都府', 'port_name' => '舞鶴西港'),
    array('id' => '308', 'prefecture_code' => '27', 'port_code' => '1', 'prefecture_name' => '大阪府', 'port_name' => '深日'),
    array('id' => '309', 'prefecture_code' => '27', 'port_code' => '2', 'prefecture_name' => '大阪府', 'port_name' => '淡輪'),
    array('id' => '310', 'prefecture_code' => '27', 'port_code' => '3', 'prefecture_name' => '大阪府', 'port_name' => '岸和田'),
    array('id' => '311', 'prefecture_code' => '27', 'port_code' => '4', 'prefecture_name' => '大阪府', 'port_name' => '泉大津'),
    array('id' => '312', 'prefecture_code' => '27', 'port_code' => '5', 'prefecture_name' => '大阪府', 'port_name' => '堺'),
    array('id' => '313', 'prefecture_code' => '27', 'port_code' => '6', 'prefecture_name' => '大阪府', 'port_name' => '大阪'),
    array('id' => '314', 'prefecture_code' => '28', 'port_code' => '1', 'prefecture_name' => '兵庫県', 'port_name' => '福良'),
    array('id' => '315', 'prefecture_code' => '28', 'port_code' => '2', 'prefecture_name' => '兵庫県', 'port_name' => '阿那賀浦'),
    array('id' => '316', 'prefecture_code' => '28', 'port_code' => '3', 'prefecture_name' => '兵庫県', 'port_name' => '由良'),
    array('id' => '317', 'prefecture_code' => '28', 'port_code' => '4', 'prefecture_name' => '兵庫県', 'port_name' => '洲本'),
    array('id' => '318', 'prefecture_code' => '28', 'port_code' => '5', 'prefecture_name' => '兵庫県', 'port_name' => '仮屋'),
    array('id' => '319', 'prefecture_code' => '28', 'port_code' => '6', 'prefecture_name' => '兵庫県', 'port_name' => '尼崎'),
    array('id' => '320', 'prefecture_code' => '28', 'port_code' => '7', 'prefecture_name' => '兵庫県', 'port_name' => '神戸'),
    array('id' => '321', 'prefecture_code' => '28', 'port_code' => '8', 'prefecture_name' => '兵庫県', 'port_name' => '苅藻島'),
    array('id' => '322', 'prefecture_code' => '28', 'port_code' => '9', 'prefecture_name' => '兵庫県', 'port_name' => '明石'),
    array('id' => '323', 'prefecture_code' => '28', 'port_code' => '10', 'prefecture_name' => '兵庫県', 'port_name' => '岩屋'),
    array('id' => '324', 'prefecture_code' => '28', 'port_code' => '11', 'prefecture_name' => '兵庫県', 'port_name' => '江崎'),
    array('id' => '325', 'prefecture_code' => '28', 'port_code' => '12', 'prefecture_name' => '兵庫県', 'port_name' => '室津'),
    array('id' => '326', 'prefecture_code' => '28', 'port_code' => '13', 'prefecture_name' => '兵庫県', 'port_name' => '江井'),
    array('id' => '327', 'prefecture_code' => '28', 'port_code' => '14', 'prefecture_name' => '兵庫県', 'port_name' => '家島'),
    array('id' => '328', 'prefecture_code' => '28', 'port_code' => '15', 'prefecture_name' => '兵庫県', 'port_name' => '二見'),
    array('id' => '329', 'prefecture_code' => '28', 'port_code' => '16', 'prefecture_name' => '兵庫県', 'port_name' => '高砂'),
    array('id' => '330', 'prefecture_code' => '28', 'port_code' => '17', 'prefecture_name' => '兵庫県', 'port_name' => '飾磨'),
    array('id' => '331', 'prefecture_code' => '28', 'port_code' => '18', 'prefecture_name' => '兵庫県', 'port_name' => '広畑'),
    array('id' => '332', 'prefecture_code' => '28', 'port_code' => '19', 'prefecture_name' => '兵庫県', 'port_name' => '相生'),
    array('id' => '333', 'prefecture_code' => '28', 'port_code' => '20', 'prefecture_name' => '兵庫県', 'port_name' => '赤穂'),
    array('id' => '334', 'prefecture_code' => '28', 'port_code' => '21', 'prefecture_name' => '兵庫県', 'port_name' => '香住'),
    array('id' => '335', 'prefecture_code' => '28', 'port_code' => '22', 'prefecture_name' => '兵庫県', 'port_name' => '柴山'),
    array('id' => '336', 'prefecture_code' => '28', 'port_code' => '23', 'prefecture_name' => '兵庫県', 'port_name' => '津居山'),
    array('id' => '337', 'prefecture_code' => '28', 'port_code' => '24', 'prefecture_name' => '兵庫県', 'port_name' => '垂水'),
    array('id' => '338', 'prefecture_code' => '30', 'port_code' => '1', 'prefecture_name' => '和歌山県', 'port_name' => '紀伊勝浦'),
    array('id' => '339', 'prefecture_code' => '30', 'port_code' => '2', 'prefecture_name' => '和歌山県', 'port_name' => '浦神'),
    array('id' => '340', 'prefecture_code' => '30', 'port_code' => '3', 'prefecture_name' => '和歌山県', 'port_name' => '串本'),
    array('id' => '341', 'prefecture_code' => '30', 'port_code' => '4', 'prefecture_name' => '和歌山県', 'port_name' => '周参見'),
    array('id' => '342', 'prefecture_code' => '30', 'port_code' => '5', 'prefecture_name' => '和歌山県', 'port_name' => '田辺（旧）'),
    array('id' => '343', 'prefecture_code' => '30', 'port_code' => '6', 'prefecture_name' => '和歌山県', 'port_name' => '三尾'),
    array('id' => '344', 'prefecture_code' => '30', 'port_code' => '7', 'prefecture_name' => '和歌山県', 'port_name' => '比井湾'),
    array('id' => '345', 'prefecture_code' => '30', 'port_code' => '8', 'prefecture_name' => '和歌山県', 'port_name' => '由良'),
    array('id' => '346', 'prefecture_code' => '30', 'port_code' => '9', 'prefecture_name' => '和歌山県', 'port_name' => '下津'),
    array('id' => '347', 'prefecture_code' => '30', 'port_code' => '10', 'prefecture_name' => '和歌山県', 'port_name' => '海南'),
    array('id' => '348', 'prefecture_code' => '30', 'port_code' => '11', 'prefecture_name' => '和歌山県', 'port_name' => '和歌山'),
    array('id' => '349', 'prefecture_code' => '30', 'port_code' => '12', 'prefecture_name' => '和歌山県', 'port_name' => '沖ノ島'),
    array('id' => '350', 'prefecture_code' => '30', 'port_code' => '13', 'prefecture_name' => '和歌山県', 'port_name' => '田辺'),
    array('id' => '351', 'prefecture_code' => '31', 'port_code' => '1', 'prefecture_name' => '鳥取県', 'port_name' => '米子'),
    array('id' => '352', 'prefecture_code' => '31', 'port_code' => '2', 'prefecture_name' => '鳥取県', 'port_name' => '境'),
    array('id' => '353', 'prefecture_code' => '31', 'port_code' => '3', 'prefecture_name' => '鳥取県', 'port_name' => '淀江'),
    array('id' => '354', 'prefecture_code' => '31', 'port_code' => '4', 'prefecture_name' => '鳥取県', 'port_name' => '赤碕'),
    array('id' => '355', 'prefecture_code' => '31', 'port_code' => '5', 'prefecture_name' => '鳥取県', 'port_name' => '因幡網代'),
    array('id' => '356', 'prefecture_code' => '31', 'port_code' => '6', 'prefecture_name' => '鳥取県', 'port_name' => '田後'),
    array('id' => '357', 'prefecture_code' => '32', 'port_code' => '1', 'prefecture_name' => '島根県', 'port_name' => '外ノ浦'),
    array('id' => '358', 'prefecture_code' => '32', 'port_code' => '2', 'prefecture_name' => '島根県', 'port_name' => '江津'),
    array('id' => '359', 'prefecture_code' => '32', 'port_code' => '3', 'prefecture_name' => '島根県', 'port_name' => '温泉津'),
    array('id' => '360', 'prefecture_code' => '32', 'port_code' => '4', 'prefecture_name' => '島根県', 'port_name' => '大社'),
    array('id' => '361', 'prefecture_code' => '32', 'port_code' => '5', 'prefecture_name' => '島根県', 'port_name' => '鷺'),
    array('id' => '362', 'prefecture_code' => '32', 'port_code' => '6', 'prefecture_name' => '島根県', 'port_name' => '河下'),
    array('id' => '363', 'prefecture_code' => '32', 'port_code' => '7', 'prefecture_name' => '島根県', 'port_name' => '恵曇'),
    array('id' => '364', 'prefecture_code' => '32', 'port_code' => '8', 'prefecture_name' => '島根県', 'port_name' => '加賀'),
    array('id' => '365', 'prefecture_code' => '32', 'port_code' => '9', 'prefecture_name' => '島根県', 'port_name' => '七類'),
    array('id' => '366', 'prefecture_code' => '32', 'port_code' => '10', 'prefecture_name' => '島根県', 'port_name' => '大根島'),
    array('id' => '367', 'prefecture_code' => '32', 'port_code' => '11', 'prefecture_name' => '島根県', 'port_name' => '安来'),
    array('id' => '368', 'prefecture_code' => '32', 'port_code' => '12', 'prefecture_name' => '島根県', 'port_name' => '浦郷'),
    array('id' => '369', 'prefecture_code' => '32', 'port_code' => '13', 'prefecture_name' => '島根県', 'port_name' => '日ノ津浦'),
    array('id' => '370', 'prefecture_code' => '32', 'port_code' => '14', 'prefecture_name' => '島根県', 'port_name' => '菱浦'),
    array('id' => '371', 'prefecture_code' => '32', 'port_code' => '15', 'prefecture_name' => '島根県', 'port_name' => '知々井'),
    array('id' => '372', 'prefecture_code' => '32', 'port_code' => '16', 'prefecture_name' => '島根県', 'port_name' => '西郷'),
    array('id' => '373', 'prefecture_code' => '32', 'port_code' => '17', 'prefecture_name' => '島根県', 'port_name' => '松江'),
    array('id' => '374', 'prefecture_code' => '33', 'port_code' => '1', 'prefecture_name' => '岡山県', 'port_name' => '片上'),
    array('id' => '375', 'prefecture_code' => '33', 'port_code' => '2', 'prefecture_name' => '岡山県', 'port_name' => '大多府島'),
    array('id' => '376', 'prefecture_code' => '33', 'port_code' => '3', 'prefecture_name' => '岡山県', 'port_name' => '牛窓'),
    array('id' => '377', 'prefecture_code' => '33', 'port_code' => '4', 'prefecture_name' => '岡山県', 'port_name' => '宝伝'),
    array('id' => '378', 'prefecture_code' => '33', 'port_code' => '5', 'prefecture_name' => '岡山県', 'port_name' => '小串'),
    array('id' => '379', 'prefecture_code' => '33', 'port_code' => '6', 'prefecture_name' => '岡山県', 'port_name' => '宇野'),
    array('id' => '380', 'prefecture_code' => '33', 'port_code' => '7', 'prefecture_name' => '岡山県', 'port_name' => '下津井'),
    array('id' => '381', 'prefecture_code' => '33', 'port_code' => '8', 'prefecture_name' => '岡山県', 'port_name' => '水島'),
    array('id' => '382', 'prefecture_code' => '33', 'port_code' => '9', 'prefecture_name' => '岡山県', 'port_name' => '笠岡'),
    array('id' => '383', 'prefecture_code' => '33', 'port_code' => '10', 'prefecture_name' => '岡山県', 'port_name' => '玉島'),
    array('id' => '384', 'prefecture_code' => '34', 'port_code' => '1', 'prefecture_name' => '広島県', 'port_name' => '福山'),
    array('id' => '385', 'prefecture_code' => '34', 'port_code' => '2', 'prefecture_name' => '広島県', 'port_name' => '鞆'),
    array('id' => '386', 'prefecture_code' => '34', 'port_code' => '3', 'prefecture_name' => '広島県', 'port_name' => '常石'),
    array('id' => '387', 'prefecture_code' => '34', 'port_code' => '4', 'prefecture_name' => '広島県', 'port_name' => '尾道'),
    array('id' => '388', 'prefecture_code' => '34', 'port_code' => '5', 'prefecture_name' => '広島県', 'port_name' => '糸崎'),
    array('id' => '389', 'prefecture_code' => '34', 'port_code' => '6', 'prefecture_name' => '広島県', 'port_name' => '江之浦'),
    array('id' => '390', 'prefecture_code' => '34', 'port_code' => '7', 'prefecture_name' => '広島県', 'port_name' => '小佐木島'),
    array('id' => '391', 'prefecture_code' => '34', 'port_code' => '8', 'prefecture_name' => '広島県', 'port_name' => '忠海'),
    array('id' => '392', 'prefecture_code' => '34', 'port_code' => '9', 'prefecture_name' => '広島県', 'port_name' => '土生'),
    array('id' => '393', 'prefecture_code' => '34', 'port_code' => '10', 'prefecture_name' => '広島県', 'port_name' => '瀬戸田'),
    array('id' => '394', 'prefecture_code' => '34', 'port_code' => '11', 'prefecture_name' => '広島県', 'port_name' => '御手洗'),
    array('id' => '395', 'prefecture_code' => '34', 'port_code' => '12', 'prefecture_name' => '広島県', 'port_name' => '小用'),
    array('id' => '396', 'prefecture_code' => '34', 'port_code' => '13', 'prefecture_name' => '広島県', 'port_name' => '長浜'),
    array('id' => '397', 'prefecture_code' => '34', 'port_code' => '14', 'prefecture_name' => '広島県', 'port_name' => '奥ノ内'),
    array('id' => '398', 'prefecture_code' => '34', 'port_code' => '15', 'prefecture_name' => '広島県', 'port_name' => '鹿老渡小瀬戸'),
    array('id' => '399', 'prefecture_code' => '34', 'port_code' => '16', 'prefecture_name' => '広島県', 'port_name' => '室尾'),
    array('id' => '400', 'prefecture_code' => '34', 'port_code' => '17', 'prefecture_name' => '広島県', 'port_name' => '美能'),
    array('id' => '401', 'prefecture_code' => '34', 'port_code' => '18', 'prefecture_name' => '広島県', 'port_name' => '江田内'),
    array('id' => '402', 'prefecture_code' => '34', 'port_code' => '19', 'prefecture_name' => '広島県', 'port_name' => '広島'),
    array('id' => '403', 'prefecture_code' => '34', 'port_code' => '20', 'prefecture_name' => '広島県', 'port_name' => '呉'),
    array('id' => '404', 'prefecture_code' => '34', 'port_code' => '21', 'prefecture_name' => '広島県', 'port_name' => '音戸瀬戸'),
    array('id' => '405', 'prefecture_code' => '34', 'port_code' => '22', 'prefecture_name' => '広島県', 'port_name' => '早瀬瀬戸'),
    array('id' => '406', 'prefecture_code' => '34', 'port_code' => '23', 'prefecture_name' => '広島県', 'port_name' => '厳島'),
    array('id' => '407', 'prefecture_code' => '34', 'port_code' => '24', 'prefecture_name' => '広島県', 'port_name' => '大野瀬戸'),
    array('id' => '408', 'prefecture_code' => '34', 'port_code' => '25', 'prefecture_name' => '広島県', 'port_name' => '竹原'),
    array('id' => '409', 'prefecture_code' => '35', 'port_code' => '1', 'prefecture_name' => '山口県', 'port_name' => '岩国'),
    array('id' => '410', 'prefecture_code' => '35', 'port_code' => '2', 'prefecture_name' => '山口県', 'port_name' => '土居'),
    array('id' => '411', 'prefecture_code' => '35', 'port_code' => '3', 'prefecture_name' => '山口県', 'port_name' => '情島'),
    array('id' => '412', 'prefecture_code' => '35', 'port_code' => '4', 'prefecture_name' => '山口県', 'port_name' => '大畠'),
    array('id' => '413', 'prefecture_code' => '35', 'port_code' => '5', 'prefecture_name' => '山口県', 'port_name' => '東安下庄'),
    array('id' => '414', 'prefecture_code' => '35', 'port_code' => '6', 'prefecture_name' => '山口県', 'port_name' => '沖家室島'),
    array('id' => '415', 'prefecture_code' => '35', 'port_code' => '7', 'prefecture_name' => '山口県', 'port_name' => '室津'),
    array('id' => '416', 'prefecture_code' => '35', 'port_code' => '8', 'prefecture_name' => '山口県', 'port_name' => '平生'),
    array('id' => '417', 'prefecture_code' => '35', 'port_code' => '9', 'prefecture_name' => '山口県', 'port_name' => '下松'),
    array('id' => '418', 'prefecture_code' => '35', 'port_code' => '10', 'prefecture_name' => '山口県', 'port_name' => '徳山'),
    array('id' => '419', 'prefecture_code' => '35', 'port_code' => '11', 'prefecture_name' => '山口県', 'port_name' => '三田尻'),
    array('id' => '420', 'prefecture_code' => '35', 'port_code' => '12', 'prefecture_name' => '山口県', 'port_name' => '宇部'),
    array('id' => '421', 'prefecture_code' => '35', 'port_code' => '13', 'prefecture_name' => '山口県', 'port_name' => '苅屋'),
    array('id' => '422', 'prefecture_code' => '35', 'port_code' => '14', 'prefecture_name' => '山口県', 'port_name' => '小野田'),
    array('id' => '423', 'prefecture_code' => '35', 'port_code' => '15', 'prefecture_name' => '山口県', 'port_name' => '長府'),
    array('id' => '424', 'prefecture_code' => '35', 'port_code' => '16', 'prefecture_name' => '山口県', 'port_name' => '岩黒'),
    array('id' => '425', 'prefecture_code' => '35', 'port_code' => '17', 'prefecture_name' => '山口県', 'port_name' => '前田'),
    array('id' => '426', 'prefecture_code' => '35', 'port_code' => '18', 'prefecture_name' => '山口県', 'port_name' => '壇之浦'),
    array('id' => '427', 'prefecture_code' => '35', 'port_code' => '19', 'prefecture_name' => '山口県', 'port_name' => '下関第１突堤'),
    array('id' => '428', 'prefecture_code' => '35', 'port_code' => '20', 'prefecture_name' => '山口県', 'port_name' => '弟子待'),
    array('id' => '429', 'prefecture_code' => '35', 'port_code' => '21', 'prefecture_name' => '山口県', 'port_name' => '田の首'),
    array('id' => '430', 'prefecture_code' => '35', 'port_code' => '22', 'prefecture_name' => '山口県', 'port_name' => '南風泊'),
    array('id' => '431', 'prefecture_code' => '35', 'port_code' => '23', 'prefecture_name' => '山口県', 'port_name' => '伊崎'),
    array('id' => '432', 'prefecture_code' => '35', 'port_code' => '24', 'prefecture_name' => '山口県', 'port_name' => '吉母'),
    array('id' => '433', 'prefecture_code' => '35', 'port_code' => '25', 'prefecture_name' => '山口県', 'port_name' => '特牛'),
    array('id' => '434', 'prefecture_code' => '35', 'port_code' => '26', 'prefecture_name' => '山口県', 'port_name' => '油谷'),
    array('id' => '435', 'prefecture_code' => '35', 'port_code' => '27', 'prefecture_name' => '山口県', 'port_name' => '宇津'),
    array('id' => '436', 'prefecture_code' => '35', 'port_code' => '28', 'prefecture_name' => '山口県', 'port_name' => '大泊'),
    array('id' => '437', 'prefecture_code' => '35', 'port_code' => '29', 'prefecture_name' => '山口県', 'port_name' => '萩'),
    array('id' => '438', 'prefecture_code' => '35', 'port_code' => '30', 'prefecture_name' => '山口県', 'port_name' => '江崎'),
    array('id' => '439', 'prefecture_code' => '35', 'port_code' => '31', 'prefecture_name' => '山口県', 'port_name' => '大山ノ鼻'),
    array('id' => '440', 'prefecture_code' => '36', 'port_code' => '1', 'prefecture_name' => '徳島県', 'port_name' => '日和佐'),
    array('id' => '441', 'prefecture_code' => '36', 'port_code' => '2', 'prefecture_name' => '徳島県', 'port_name' => '橘'),
    array('id' => '442', 'prefecture_code' => '36', 'port_code' => '3', 'prefecture_name' => '徳島県', 'port_name' => '富岡'),
    array('id' => '443', 'prefecture_code' => '36', 'port_code' => '4', 'prefecture_name' => '徳島県', 'port_name' => '小松島'),
    array('id' => '444', 'prefecture_code' => '36', 'port_code' => '5', 'prefecture_name' => '徳島県', 'port_name' => '土佐泊'),
    array('id' => '445', 'prefecture_code' => '36', 'port_code' => '6', 'prefecture_name' => '徳島県', 'port_name' => '堂ノ浦'),
    array('id' => '446', 'prefecture_code' => '36', 'port_code' => '7', 'prefecture_name' => '徳島県', 'port_name' => '北泊'),
    array('id' => '447', 'prefecture_code' => '36', 'port_code' => '8', 'prefecture_name' => '徳島県', 'port_name' => '孫埼'),
    array('id' => '448', 'prefecture_code' => '36', 'port_code' => '9', 'prefecture_name' => '徳島県', 'port_name' => '網代'),
    array('id' => '449', 'prefecture_code' => '36', 'port_code' => '10', 'prefecture_name' => '徳島県', 'port_name' => '粟津'),
    array('id' => '450', 'prefecture_code' => '37', 'port_code' => '1', 'prefecture_name' => '香川県', 'port_name' => '引田'),
    array('id' => '451', 'prefecture_code' => '37', 'port_code' => '2', 'prefecture_name' => '香川県', 'port_name' => '坂手'),
    array('id' => '452', 'prefecture_code' => '37', 'port_code' => '3', 'prefecture_name' => '香川県', 'port_name' => '大部'),
    array('id' => '453', 'prefecture_code' => '37', 'port_code' => '4', 'prefecture_name' => '香川県', 'port_name' => '地蔵埼'),
    array('id' => '454', 'prefecture_code' => '37', 'port_code' => '5', 'prefecture_name' => '香川県', 'port_name' => '入部'),
    array('id' => '455', 'prefecture_code' => '37', 'port_code' => '6', 'prefecture_name' => '香川県', 'port_name' => '宮ノ浦'),
    array('id' => '456', 'prefecture_code' => '37', 'port_code' => '7', 'prefecture_name' => '香川県', 'port_name' => '男木島'),
    array('id' => '457', 'prefecture_code' => '37', 'port_code' => '8', 'prefecture_name' => '香川県', 'port_name' => '高松'),
    array('id' => '458', 'prefecture_code' => '37', 'port_code' => '9', 'prefecture_name' => '香川県', 'port_name' => '坂出'),
    array('id' => '459', 'prefecture_code' => '37', 'port_code' => '10', 'prefecture_name' => '香川県', 'port_name' => '丸亀'),
    array('id' => '460', 'prefecture_code' => '37', 'port_code' => '11', 'prefecture_name' => '香川県', 'port_name' => '鍋島'),
    array('id' => '461', 'prefecture_code' => '37', 'port_code' => '12', 'prefecture_name' => '香川県', 'port_name' => '与島'),
    array('id' => '462', 'prefecture_code' => '37', 'port_code' => '13', 'prefecture_name' => '香川県', 'port_name' => '青木'),
    array('id' => '463', 'prefecture_code' => '37', 'port_code' => '14', 'prefecture_name' => '香川県', 'port_name' => '佐柳'),
    array('id' => '464', 'prefecture_code' => '37', 'port_code' => '15', 'prefecture_name' => '香川県', 'port_name' => '粟島'),
    array('id' => '465', 'prefecture_code' => '37', 'port_code' => '16', 'prefecture_name' => '香川県', 'port_name' => '観音寺'),
    array('id' => '466', 'prefecture_code' => '38', 'port_code' => '1', 'prefecture_name' => '愛媛県', 'port_name' => '三島'),
    array('id' => '467', 'prefecture_code' => '38', 'port_code' => '2', 'prefecture_name' => '愛媛県', 'port_name' => '多喜浜'),
    array('id' => '468', 'prefecture_code' => '38', 'port_code' => '3', 'prefecture_name' => '愛媛県', 'port_name' => '新居浜'),
    array('id' => '469', 'prefecture_code' => '38', 'port_code' => '4', 'prefecture_name' => '愛媛県', 'port_name' => '西条'),
    array('id' => '470', 'prefecture_code' => '38', 'port_code' => '5', 'prefecture_name' => '愛媛県', 'port_name' => '家ノ島'),
    array('id' => '471', 'prefecture_code' => '38', 'port_code' => '6', 'prefecture_name' => '愛媛県', 'port_name' => '今治'),
    array('id' => '472', 'prefecture_code' => '38', 'port_code' => '7', 'prefecture_name' => '愛媛県', 'port_name' => '来島'),
    array('id' => '473', 'prefecture_code' => '38', 'port_code' => '8', 'prefecture_name' => '愛媛県', 'port_name' => '波止浜'),
    array('id' => '474', 'prefecture_code' => '38', 'port_code' => '9', 'prefecture_name' => '愛媛県', 'port_name' => '菊間'),
    array('id' => '475', 'prefecture_code' => '38', 'port_code' => '10', 'prefecture_name' => '愛媛県', 'port_name' => '宇和間'),
    array('id' => '476', 'prefecture_code' => '38', 'port_code' => '11', 'prefecture_name' => '愛媛県', 'port_name' => '大浦'),
    array('id' => '477', 'prefecture_code' => '38', 'port_code' => '12', 'prefecture_name' => '愛媛県', 'port_name' => '興居島'),
    array('id' => '478', 'prefecture_code' => '38', 'port_code' => '13', 'prefecture_name' => '愛媛県', 'port_name' => '松山'),
    array('id' => '479', 'prefecture_code' => '38', 'port_code' => '14', 'prefecture_name' => '愛媛県', 'port_name' => '青島'),
    array('id' => '480', 'prefecture_code' => '38', 'port_code' => '15', 'prefecture_name' => '愛媛県', 'port_name' => '長浜'),
    array('id' => '481', 'prefecture_code' => '38', 'port_code' => '16', 'prefecture_name' => '愛媛県', 'port_name' => '三机'),
    array('id' => '482', 'prefecture_code' => '38', 'port_code' => '17', 'prefecture_name' => '愛媛県', 'port_name' => '与侈'),
    array('id' => '483', 'prefecture_code' => '38', 'port_code' => '18', 'prefecture_name' => '愛媛県', 'port_name' => '内ノ浦'),
    array('id' => '484', 'prefecture_code' => '38', 'port_code' => '19', 'prefecture_name' => '愛媛県', 'port_name' => '八幡浜'),
    array('id' => '485', 'prefecture_code' => '38', 'port_code' => '20', 'prefecture_name' => '愛媛県', 'port_name' => '奥地湾'),
    array('id' => '486', 'prefecture_code' => '38', 'port_code' => '21', 'prefecture_name' => '愛媛県', 'port_name' => '宇和島'),
    array('id' => '487', 'prefecture_code' => '38', 'port_code' => '22', 'prefecture_name' => '愛媛県', 'port_name' => '能登'),
    array('id' => '488', 'prefecture_code' => '38', 'port_code' => '23', 'prefecture_name' => '愛媛県', 'port_name' => '柏崎'),
    array('id' => '489', 'prefecture_code' => '38', 'port_code' => '24', 'prefecture_name' => '愛媛県', 'port_name' => '小島'),
    array('id' => '490', 'prefecture_code' => '38', 'port_code' => '25', 'prefecture_name' => '愛媛県', 'port_name' => '鼻栗瀬戸'),
    array('id' => '491', 'prefecture_code' => '39', 'port_code' => '1', 'prefecture_name' => '高知県', 'port_name' => '甲浦'),
    array('id' => '492', 'prefecture_code' => '39', 'port_code' => '2', 'prefecture_name' => '高知県', 'port_name' => '室戸岬'),
    array('id' => '493', 'prefecture_code' => '39', 'port_code' => '3', 'prefecture_name' => '高知県', 'port_name' => '室津'),
    array('id' => '494', 'prefecture_code' => '39', 'port_code' => '4', 'prefecture_name' => '高知県', 'port_name' => '高知'),
    array('id' => '495', 'prefecture_code' => '39', 'port_code' => '5', 'prefecture_name' => '高知県', 'port_name' => '須崎'),
    array('id' => '496', 'prefecture_code' => '39', 'port_code' => '6', 'prefecture_name' => '高知県', 'port_name' => '土佐清水'),
    array('id' => '497', 'prefecture_code' => '39', 'port_code' => '7', 'prefecture_name' => '高知県', 'port_name' => '片島'),
    array('id' => '498', 'prefecture_code' => '40', 'port_code' => '1', 'prefecture_name' => '福岡県', 'port_name' => '宇島'),
    array('id' => '499', 'prefecture_code' => '40', 'port_code' => '2', 'prefecture_name' => '福岡県', 'port_name' => '苅田'),
    array('id' => '500', 'prefecture_code' => '40', 'port_code' => '3', 'prefecture_name' => '福岡県', 'port_name' => '新門司'),
    array('id' => '501', 'prefecture_code' => '40', 'port_code' => '4', 'prefecture_name' => '福岡県', 'port_name' => '青浜'),
    array('id' => '502', 'prefecture_code' => '40', 'port_code' => '5', 'prefecture_name' => '福岡県', 'port_name' => '田野浦'),
    array('id' => '503', 'prefecture_code' => '40', 'port_code' => '6', 'prefecture_name' => '福岡県', 'port_name' => '旧門司'),
    array('id' => '504', 'prefecture_code' => '40', 'port_code' => '7', 'prefecture_name' => '福岡県', 'port_name' => '西海岸'),
    array('id' => '505', 'prefecture_code' => '40', 'port_code' => '8', 'prefecture_name' => '福岡県', 'port_name' => '砂津'),
    array('id' => '506', 'prefecture_code' => '40', 'port_code' => '9', 'prefecture_name' => '福岡県', 'port_name' => '製鉄戸畑泊地'),
    array('id' => '507', 'prefecture_code' => '40', 'port_code' => '10', 'prefecture_name' => '福岡県', 'port_name' => '若松'),
    array('id' => '508', 'prefecture_code' => '40', 'port_code' => '11', 'prefecture_name' => '福岡県', 'port_name' => '戸畑'),
    array('id' => '509', 'prefecture_code' => '40', 'port_code' => '12', 'prefecture_name' => '福岡県', 'port_name' => '八幡'),
    array('id' => '510', 'prefecture_code' => '40', 'port_code' => '13', 'prefecture_name' => '福岡県', 'port_name' => '沖'),
    array('id' => '511', 'prefecture_code' => '40', 'port_code' => '14', 'prefecture_name' => '福岡県', 'port_name' => '白島'),
    array('id' => '512', 'prefecture_code' => '40', 'port_code' => '15', 'prefecture_name' => '福岡県', 'port_name' => '岩屋'),
    array('id' => '513', 'prefecture_code' => '40', 'port_code' => '16', 'prefecture_name' => '福岡県', 'port_name' => '鐘崎'),
    array('id' => '514', 'prefecture_code' => '40', 'port_code' => '17', 'prefecture_name' => '福岡県', 'port_name' => '神湊'),
    array('id' => '515', 'prefecture_code' => '40', 'port_code' => '18', 'prefecture_name' => '福岡県', 'port_name' => '津屋崎'),
    array('id' => '516', 'prefecture_code' => '40', 'port_code' => '19', 'prefecture_name' => '福岡県', 'port_name' => '西戸埼'),
    array('id' => '517', 'prefecture_code' => '40', 'port_code' => '20', 'prefecture_name' => '福岡県', 'port_name' => '博多船だまり'),
    array('id' => '518', 'prefecture_code' => '40', 'port_code' => '21', 'prefecture_name' => '福岡県', 'port_name' => '福岡船だまり'),
    array('id' => '519', 'prefecture_code' => '40', 'port_code' => '22', 'prefecture_name' => '福岡県', 'port_name' => '若松（響灘）'),
    array('id' => '520', 'prefecture_code' => '40', 'port_code' => '23', 'prefecture_name' => '福岡県', 'port_name' => '三池'),
    array('id' => '521', 'prefecture_code' => '40', 'port_code' => '24', 'prefecture_name' => '福岡県', 'port_name' => '筑前大島'),
    array('id' => '522', 'prefecture_code' => '40', 'port_code' => '25', 'prefecture_name' => '福岡県', 'port_name' => '柏原'),
    array('id' => '523', 'prefecture_code' => '40', 'port_code' => '26', 'prefecture_name' => '福岡県', 'port_name' => '脇田'),
    array('id' => '524', 'prefecture_code' => '40', 'port_code' => '27', 'prefecture_name' => '福岡県', 'port_name' => '日明'),
    array('id' => '525', 'prefecture_code' => '40', 'port_code' => '28', 'prefecture_name' => '福岡県', 'port_name' => '小呂島'),
    array('id' => '526', 'prefecture_code' => '41', 'port_code' => '1', 'prefecture_name' => '佐賀県', 'port_name' => '唐津'),
    array('id' => '527', 'prefecture_code' => '41', 'port_code' => '2', 'prefecture_name' => '佐賀県', 'port_name' => '呼子'),
    array('id' => '528', 'prefecture_code' => '41', 'port_code' => '3', 'prefecture_name' => '佐賀県', 'port_name' => '名護屋浦'),
    array('id' => '529', 'prefecture_code' => '41', 'port_code' => '4', 'prefecture_name' => '佐賀県', 'port_name' => '仮屋'),
    array('id' => '530', 'prefecture_code' => '41', 'port_code' => '5', 'prefecture_name' => '佐賀県', 'port_name' => '波瀬'),
    array('id' => '531', 'prefecture_code' => '41', 'port_code' => '6', 'prefecture_name' => '佐賀県', 'port_name' => '竹崎島'),
    array('id' => '532', 'prefecture_code' => '41', 'port_code' => '7', 'prefecture_name' => '佐賀県', 'port_name' => '住ノ江'),
    array('id' => '533', 'prefecture_code' => '41', 'port_code' => '8', 'prefecture_name' => '佐賀県', 'port_name' => '若津'),
    array('id' => '534', 'prefecture_code' => '42', 'port_code' => '1', 'prefecture_name' => '長崎県', 'port_name' => '新御厨'),
    array('id' => '535', 'prefecture_code' => '42', 'port_code' => '2', 'prefecture_name' => '長崎県', 'port_name' => '大飛島'),
    array('id' => '536', 'prefecture_code' => '42', 'port_code' => '3', 'prefecture_name' => '長崎県', 'port_name' => '郷ノ浦'),
    array('id' => '537', 'prefecture_code' => '42', 'port_code' => '4', 'prefecture_name' => '長崎県', 'port_name' => '勝本'),
    array('id' => '538', 'prefecture_code' => '42', 'port_code' => '5', 'prefecture_name' => '長崎県', 'port_name' => '芦辺'),
    array('id' => '539', 'prefecture_code' => '42', 'port_code' => '6', 'prefecture_name' => '長崎県', 'port_name' => '厳原'),
    array('id' => '540', 'prefecture_code' => '42', 'port_code' => '7', 'prefecture_name' => '長崎県', 'port_name' => '高浜'),
    array('id' => '541', 'prefecture_code' => '42', 'port_code' => '8', 'prefecture_name' => '長崎県', 'port_name' => '大船越'),
    array('id' => '542', 'prefecture_code' => '42', 'port_code' => '9', 'prefecture_name' => '長崎県', 'port_name' => '茂土浦'),
    array('id' => '543', 'prefecture_code' => '42', 'port_code' => '10', 'prefecture_name' => '長崎県', 'port_name' => '鴨居瀬'),
    array('id' => '544', 'prefecture_code' => '42', 'port_code' => '11', 'prefecture_name' => '長崎県', 'port_name' => '千尋藻'),
    array('id' => '545', 'prefecture_code' => '42', 'port_code' => '12', 'prefecture_name' => '長崎県', 'port_name' => '佐賀'),
    array('id' => '546', 'prefecture_code' => '42', 'port_code' => '13', 'prefecture_name' => '長崎県', 'port_name' => '小鹿湾'),
    array('id' => '547', 'prefecture_code' => '42', 'port_code' => '14', 'prefecture_name' => '長崎県', 'port_name' => '網代'),
    array('id' => '548', 'prefecture_code' => '42', 'port_code' => '15', 'prefecture_name' => '長崎県', 'port_name' => '泉'),
    array('id' => '549', 'prefecture_code' => '42', 'port_code' => '16', 'prefecture_name' => '長崎県', 'port_name' => '大河内湾'),
    array('id' => '550', 'prefecture_code' => '42', 'port_code' => '17', 'prefecture_name' => '長崎県', 'port_name' => '佐須奈'),
    array('id' => '551', 'prefecture_code' => '42', 'port_code' => '18', 'prefecture_name' => '長崎県', 'port_name' => '伊奈'),
    array('id' => '552', 'prefecture_code' => '42', 'port_code' => '19', 'prefecture_name' => '長崎県', 'port_name' => '狩尾'),
    array('id' => '553', 'prefecture_code' => '42', 'port_code' => '20', 'prefecture_name' => '長崎県', 'port_name' => '綱湾'),
    array('id' => '554', 'prefecture_code' => '42', 'port_code' => '21', 'prefecture_name' => '長崎県', 'port_name' => '廻'),
    array('id' => '555', 'prefecture_code' => '42', 'port_code' => '22', 'prefecture_name' => '長崎県', 'port_name' => '尾崎浦'),
    array('id' => '556', 'prefecture_code' => '42', 'port_code' => '23', 'prefecture_name' => '長崎県', 'port_name' => '箕形'),
    array('id' => '557', 'prefecture_code' => '42', 'port_code' => '24', 'prefecture_name' => '長崎県', 'port_name' => '昼ヶ浦'),
    array('id' => '558', 'prefecture_code' => '42', 'port_code' => '25', 'prefecture_name' => '長崎県', 'port_name' => '竹敷'),
    array('id' => '559', 'prefecture_code' => '42', 'port_code' => '26', 'prefecture_name' => '長崎県', 'port_name' => '島山'),
    array('id' => '560', 'prefecture_code' => '42', 'port_code' => '27', 'prefecture_name' => '長崎県', 'port_name' => '大山浦'),
    array('id' => '561', 'prefecture_code' => '42', 'port_code' => '28', 'prefecture_name' => '長崎県', 'port_name' => '万関瀬戸東口'),
    array('id' => '562', 'prefecture_code' => '42', 'port_code' => '29', 'prefecture_name' => '長崎県', 'port_name' => '万関瀬戸西口'),
    array('id' => '563', 'prefecture_code' => '42', 'port_code' => '30', 'prefecture_name' => '長崎県', 'port_name' => '小茂田'),
    array('id' => '564', 'prefecture_code' => '42', 'port_code' => '31', 'prefecture_name' => '長崎県', 'port_name' => '久根浜'),
    array('id' => '565', 'prefecture_code' => '42', 'port_code' => '32', 'prefecture_name' => '長崎県', 'port_name' => '豆酘'),
    array('id' => '566', 'prefecture_code' => '42', 'port_code' => '33', 'prefecture_name' => '長崎県', 'port_name' => '黒子島'),
    array('id' => '567', 'prefecture_code' => '42', 'port_code' => '34', 'prefecture_name' => '長崎県', 'port_name' => '薄香湾'),
    array('id' => '568', 'prefecture_code' => '42', 'port_code' => '35', 'prefecture_name' => '長崎県', 'port_name' => '志々伎湾'),
    array('id' => '569', 'prefecture_code' => '42', 'port_code' => '36', 'prefecture_name' => '長崎県', 'port_name' => '楠泊'),
    array('id' => '570', 'prefecture_code' => '42', 'port_code' => '37', 'prefecture_name' => '長崎県', 'port_name' => '相ノ浦'),
    array('id' => '571', 'prefecture_code' => '42', 'port_code' => '38', 'prefecture_name' => '長崎県', 'port_name' => '高後埼'),
    array('id' => '572', 'prefecture_code' => '42', 'port_code' => '39', 'prefecture_name' => '長崎県', 'port_name' => '俵ヶ浦'),
    array('id' => '573', 'prefecture_code' => '42', 'port_code' => '40', 'prefecture_name' => '長崎県', 'port_name' => '佐世保'),
    array('id' => '574', 'prefecture_code' => '42', 'port_code' => '41', 'prefecture_name' => '長崎県', 'port_name' => '巣喰ノ浦'),
    array('id' => '575', 'prefecture_code' => '42', 'port_code' => '42', 'prefecture_name' => '長崎県', 'port_name' => '鯛ノ浦'),
    array('id' => '576', 'prefecture_code' => '42', 'port_code' => '43', 'prefecture_name' => '長崎県', 'port_name' => '小鯛'),
    array('id' => '577', 'prefecture_code' => '42', 'port_code' => '44', 'prefecture_name' => '長崎県', 'port_name' => '畑下'),
    array('id' => '578', 'prefecture_code' => '42', 'port_code' => '45', 'prefecture_name' => '長崎県', 'port_name' => '名倉'),
    array('id' => '579', 'prefecture_code' => '42', 'port_code' => '46', 'prefecture_name' => '長崎県', 'port_name' => '伊ノ浦'),
    array('id' => '580', 'prefecture_code' => '42', 'port_code' => '47', 'prefecture_name' => '長崎県', 'port_name' => '早岐突堤（北側）'),
    array('id' => '581', 'prefecture_code' => '42', 'port_code' => '48', 'prefecture_name' => '長崎県', 'port_name' => '早岐突堤（南側）'),
    array('id' => '582', 'prefecture_code' => '42', 'port_code' => '49', 'prefecture_name' => '長崎県', 'port_name' => '小串湾'),
    array('id' => '583', 'prefecture_code' => '42', 'port_code' => '50', 'prefecture_name' => '長崎県', 'port_name' => '大村'),
    array('id' => '584', 'prefecture_code' => '42', 'port_code' => '51', 'prefecture_name' => '長崎県', 'port_name' => '面高湾'),
    array('id' => '585', 'prefecture_code' => '42', 'port_code' => '52', 'prefecture_name' => '長崎県', 'port_name' => '肥前大島'),
    array('id' => '586', 'prefecture_code' => '42', 'port_code' => '53', 'prefecture_name' => '長崎県', 'port_name' => '崎戸'),
    array('id' => '587', 'prefecture_code' => '42', 'port_code' => '54', 'prefecture_name' => '長崎県', 'port_name' => '松島'),
    array('id' => '588', 'prefecture_code' => '42', 'port_code' => '55', 'prefecture_name' => '長崎県', 'port_name' => '小江'),
    array('id' => '589', 'prefecture_code' => '42', 'port_code' => '56', 'prefecture_name' => '長崎県', 'port_name' => '伊王島'),
    array('id' => '590', 'prefecture_code' => '42', 'port_code' => '57', 'prefecture_name' => '長崎県', 'port_name' => '鼠島'),
    array('id' => '591', 'prefecture_code' => '42', 'port_code' => '58', 'prefecture_name' => '長崎県', 'port_name' => '女神'),
    array('id' => '592', 'prefecture_code' => '42', 'port_code' => '59', 'prefecture_name' => '長崎県', 'port_name' => '松ケ枝'),
    array('id' => '593', 'prefecture_code' => '42', 'port_code' => '60', 'prefecture_name' => '長崎県', 'port_name' => '水ノ浦'),
    array('id' => '594', 'prefecture_code' => '42', 'port_code' => '61', 'prefecture_name' => '長崎県', 'port_name' => '深堀'),
    array('id' => '595', 'prefecture_code' => '42', 'port_code' => '62', 'prefecture_name' => '長崎県', 'port_name' => '高島'),
    array('id' => '596', 'prefecture_code' => '42', 'port_code' => '63', 'prefecture_name' => '長崎県', 'port_name' => '樺島水道'),
    array('id' => '597', 'prefecture_code' => '42', 'port_code' => '64', 'prefecture_name' => '長崎県', 'port_name' => '神ノ浦'),
    array('id' => '598', 'prefecture_code' => '42', 'port_code' => '65', 'prefecture_name' => '長崎県', 'port_name' => '笛吹'),
    array('id' => '599', 'prefecture_code' => '42', 'port_code' => '66', 'prefecture_name' => '長崎県', 'port_name' => '有川'),
    array('id' => '600', 'prefecture_code' => '42', 'port_code' => '67', 'prefecture_name' => '長崎県', 'port_name' => '鯛之浦'),
    array('id' => '601', 'prefecture_code' => '42', 'port_code' => '68', 'prefecture_name' => '長崎県', 'port_name' => '荒川'),
    array('id' => '602', 'prefecture_code' => '42', 'port_code' => '69', 'prefecture_name' => '長崎県', 'port_name' => '若松'),
    array('id' => '603', 'prefecture_code' => '42', 'port_code' => '70', 'prefecture_name' => '長崎県', 'port_name' => '船廻湾'),
    array('id' => '604', 'prefecture_code' => '42', 'port_code' => '71', 'prefecture_name' => '長崎県', 'port_name' => '戸岐浦'),
    array('id' => '605', 'prefecture_code' => '42', 'port_code' => '72', 'prefecture_name' => '長崎県', 'port_name' => '福江'),
    array('id' => '606', 'prefecture_code' => '42', 'port_code' => '73', 'prefecture_name' => '長崎県', 'port_name' => '富江'),
    array('id' => '607', 'prefecture_code' => '42', 'port_code' => '74', 'prefecture_name' => '長崎県', 'port_name' => '玉之浦'),
    array('id' => '608', 'prefecture_code' => '42', 'port_code' => '75', 'prefecture_name' => '長崎県', 'port_name' => '三井楽'),
    array('id' => '609', 'prefecture_code' => '42', 'port_code' => '76', 'prefecture_name' => '長崎県', 'port_name' => '水之浦'),
    array('id' => '610', 'prefecture_code' => '42', 'port_code' => '77', 'prefecture_name' => '長崎県', 'port_name' => '女島'),
    array('id' => '611', 'prefecture_code' => '42', 'port_code' => '78', 'prefecture_name' => '長崎県', 'port_name' => '網場'),
    array('id' => '612', 'prefecture_code' => '42', 'port_code' => '79', 'prefecture_name' => '長崎県', 'port_name' => '口之津'),
    array('id' => '613', 'prefecture_code' => '42', 'port_code' => '80', 'prefecture_name' => '長崎県', 'port_name' => '須川'),
    array('id' => '614', 'prefecture_code' => '42', 'port_code' => '81', 'prefecture_name' => '長崎県', 'port_name' => '島原'),
    array('id' => '615', 'prefecture_code' => '42', 'port_code' => '82', 'prefecture_name' => '長崎県', 'port_name' => '荒川'),
    array('id' => '616', 'prefecture_code' => '42', 'port_code' => '83', 'prefecture_name' => '長崎県', 'port_name' => '飯ノ瀬戸'),
    array('id' => '617', 'prefecture_code' => '42', 'port_code' => '84', 'prefecture_name' => '長崎県', 'port_name' => '神部'),
    array('id' => '618', 'prefecture_code' => '42', 'port_code' => '85', 'prefecture_name' => '長崎県', 'port_name' => '島原新港'),
    array('id' => '619', 'prefecture_code' => '42', 'port_code' => '86', 'prefecture_name' => '長崎県', 'port_name' => '万関瀬戸中央部'),
    array('id' => '620', 'prefecture_code' => '42', 'port_code' => '87', 'prefecture_name' => '長崎県', 'port_name' => '青方'),
    array('id' => '621', 'prefecture_code' => '42', 'port_code' => '88', 'prefecture_name' => '長崎県', 'port_name' => '松浦'),
    array('id' => '622', 'prefecture_code' => '43', 'port_code' => '1', 'prefecture_name' => '熊本県', 'port_name' => '本渡'),
    array('id' => '623', 'prefecture_code' => '43', 'port_code' => '2', 'prefecture_name' => '熊本県', 'port_name' => '長洲'),
    array('id' => '624', 'prefecture_code' => '43', 'port_code' => '3', 'prefecture_name' => '熊本県', 'port_name' => '熊本'),
    array('id' => '625', 'prefecture_code' => '43', 'port_code' => '4', 'prefecture_name' => '熊本県', 'port_name' => '三角'),
    array('id' => '626', 'prefecture_code' => '43', 'port_code' => '5', 'prefecture_name' => '熊本県', 'port_name' => '蔵々ノ瀬戸'),
    array('id' => '627', 'prefecture_code' => '43', 'port_code' => '6', 'prefecture_name' => '熊本県', 'port_name' => '柳ノ瀬戸'),
    array('id' => '628', 'prefecture_code' => '43', 'port_code' => '7', 'prefecture_name' => '熊本県', 'port_name' => '八代'),
    array('id' => '629', 'prefecture_code' => '43', 'port_code' => '8', 'prefecture_name' => '熊本県', 'port_name' => '加賀島'),
    array('id' => '630', 'prefecture_code' => '43', 'port_code' => '9', 'prefecture_name' => '熊本県', 'port_name' => '池ノ浦'),
    array('id' => '631', 'prefecture_code' => '43', 'port_code' => '10', 'prefecture_name' => '熊本県', 'port_name' => '水俣'),
    array('id' => '632', 'prefecture_code' => '43', 'port_code' => '11', 'prefecture_name' => '熊本県', 'port_name' => '袋浦'),
    array('id' => '633', 'prefecture_code' => '43', 'port_code' => '12', 'prefecture_name' => '熊本県', 'port_name' => '富岡'),
    array('id' => '634', 'prefecture_code' => '43', 'port_code' => '13', 'prefecture_name' => '熊本県', 'port_name' => '崎津湾'),
    array('id' => '635', 'prefecture_code' => '43', 'port_code' => '14', 'prefecture_name' => '熊本県', 'port_name' => '牛深'),
    array('id' => '636', 'prefecture_code' => '43', 'port_code' => '15', 'prefecture_name' => '熊本県', 'port_name' => '大門'),
    array('id' => '637', 'prefecture_code' => '44', 'port_code' => '1', 'prefecture_name' => '大分県', 'port_name' => '佐賀関'),
    array('id' => '638', 'prefecture_code' => '44', 'port_code' => '2', 'prefecture_name' => '大分県', 'port_name' => '鶴崎'),
    array('id' => '639', 'prefecture_code' => '44', 'port_code' => '3', 'prefecture_name' => '大分県', 'port_name' => '西大分'),
    array('id' => '640', 'prefecture_code' => '44', 'port_code' => '4', 'prefecture_name' => '大分県', 'port_name' => '亀川'),
    array('id' => '641', 'prefecture_code' => '44', 'port_code' => '5', 'prefecture_name' => '大分県', 'port_name' => '日出'),
    array('id' => '642', 'prefecture_code' => '44', 'port_code' => '6', 'prefecture_name' => '大分県', 'port_name' => '姫島'),
    array('id' => '643', 'prefecture_code' => '44', 'port_code' => '7', 'prefecture_name' => '大分県', 'port_name' => '香々地'),
    array('id' => '644', 'prefecture_code' => '44', 'port_code' => '8', 'prefecture_name' => '大分県', 'port_name' => '高田'),
    array('id' => '645', 'prefecture_code' => '44', 'port_code' => '9', 'prefecture_name' => '大分県', 'port_name' => '中津'),
    array('id' => '646', 'prefecture_code' => '44', 'port_code' => '10', 'prefecture_name' => '大分県', 'port_name' => '下浦'),
    array('id' => '647', 'prefecture_code' => '44', 'port_code' => '11', 'prefecture_name' => '大分県', 'port_name' => '泊ヶ内'),
    array('id' => '648', 'prefecture_code' => '44', 'port_code' => '12', 'prefecture_name' => '大分県', 'port_name' => '津久見'),
    array('id' => '649', 'prefecture_code' => '44', 'port_code' => '13', 'prefecture_name' => '大分県', 'port_name' => '葛'),
    array('id' => '650', 'prefecture_code' => '44', 'port_code' => '14', 'prefecture_name' => '大分県', 'port_name' => '長島'),
    array('id' => '651', 'prefecture_code' => '44', 'port_code' => '15', 'prefecture_name' => '大分県', 'port_name' => '大島'),
    array('id' => '652', 'prefecture_code' => '44', 'port_code' => '16', 'prefecture_name' => '大分県', 'port_name' => '猪串'),
    array('id' => '653', 'prefecture_code' => '44', 'port_code' => '17', 'prefecture_name' => '大分県', 'port_name' => '蒲江'),
    array('id' => '654', 'prefecture_code' => '44', 'port_code' => '18', 'prefecture_name' => '大分県', 'port_name' => '米水津泊地'),
    array('id' => '655', 'prefecture_code' => '45', 'port_code' => '1', 'prefecture_name' => '宮崎県', 'port_name' => '福島'),
    array('id' => '656', 'prefecture_code' => '45', 'port_code' => '2', 'prefecture_name' => '宮崎県', 'port_name' => '外浦'),
    array('id' => '657', 'prefecture_code' => '45', 'port_code' => '3', 'prefecture_name' => '宮崎県', 'port_name' => '油津'),
    array('id' => '658', 'prefecture_code' => '45', 'port_code' => '4', 'prefecture_name' => '宮崎県', 'port_name' => '内海'),
    array('id' => '659', 'prefecture_code' => '45', 'port_code' => '5', 'prefecture_name' => '宮崎県', 'port_name' => '折生迫'),
    array('id' => '660', 'prefecture_code' => '45', 'port_code' => '6', 'prefecture_name' => '宮崎県', 'port_name' => '細島'),
    array('id' => '661', 'prefecture_code' => '45', 'port_code' => '7', 'prefecture_name' => '宮崎県', 'port_name' => '美々津'),
    array('id' => '662', 'prefecture_code' => '45', 'port_code' => '8', 'prefecture_name' => '宮崎県', 'port_name' => '土々呂'),
    array('id' => '663', 'prefecture_code' => '45', 'port_code' => '9', 'prefecture_name' => '宮崎県', 'port_name' => '宮崎'),
    array('id' => '664', 'prefecture_code' => '46', 'port_code' => '1', 'prefecture_name' => '鹿児島県', 'port_name' => '阿久根'),
    array('id' => '665', 'prefecture_code' => '46', 'port_code' => '2', 'prefecture_name' => '鹿児島県', 'port_name' => '川内'),
    array('id' => '666', 'prefecture_code' => '46', 'port_code' => '3', 'prefecture_name' => '鹿児島県', 'port_name' => '浦内湾'),
    array('id' => '667', 'prefecture_code' => '46', 'port_code' => '4', 'prefecture_name' => '鹿児島県', 'port_name' => '串木野'),
    array('id' => '668', 'prefecture_code' => '46', 'port_code' => '5', 'prefecture_name' => '鹿児島県', 'port_name' => '戸崎'),
    array('id' => '669', 'prefecture_code' => '46', 'port_code' => '6', 'prefecture_name' => '鹿児島県', 'port_name' => '坊泊'),
    array('id' => '670', 'prefecture_code' => '46', 'port_code' => '7', 'prefecture_name' => '鹿児島県', 'port_name' => '枕崎'),
    array('id' => '671', 'prefecture_code' => '46', 'port_code' => '8', 'prefecture_name' => '鹿児島県', 'port_name' => '山川'),
    array('id' => '672', 'prefecture_code' => '46', 'port_code' => '9', 'prefecture_name' => '鹿児島県', 'port_name' => '喜入'),
    array('id' => '673', 'prefecture_code' => '46', 'port_code' => '10', 'prefecture_name' => '鹿児島県', 'port_name' => '鹿児島'),
    array('id' => '674', 'prefecture_code' => '46', 'port_code' => '11', 'prefecture_name' => '鹿児島県', 'port_name' => '麓'),
    array('id' => '675', 'prefecture_code' => '46', 'port_code' => '12', 'prefecture_name' => '鹿児島県', 'port_name' => '園山'),
    array('id' => '676', 'prefecture_code' => '46', 'port_code' => '13', 'prefecture_name' => '鹿児島県', 'port_name' => '垂水'),
    array('id' => '677', 'prefecture_code' => '46', 'port_code' => '14', 'prefecture_name' => '鹿児島県', 'port_name' => '鹿屋'),
    array('id' => '678', 'prefecture_code' => '46', 'port_code' => '15', 'prefecture_name' => '鹿児島県', 'port_name' => '伊座敷'),
    array('id' => '679', 'prefecture_code' => '46', 'port_code' => '16', 'prefecture_name' => '鹿児島県', 'port_name' => '大泊'),
    array('id' => '680', 'prefecture_code' => '46', 'port_code' => '17', 'prefecture_name' => '鹿児島県', 'port_name' => '志布志'),
    array('id' => '681', 'prefecture_code' => '46', 'port_code' => '18', 'prefecture_name' => '鹿児島県', 'port_name' => '硫黄島'),
    array('id' => '682', 'prefecture_code' => '46', 'port_code' => '19', 'prefecture_name' => '鹿児島県', 'port_name' => '西之表'),
    array('id' => '683', 'prefecture_code' => '46', 'port_code' => '20', 'prefecture_name' => '鹿児島県', 'port_name' => '田ノ脇'),
    array('id' => '684', 'prefecture_code' => '46', 'port_code' => '21', 'prefecture_name' => '鹿児島県', 'port_name' => '大浦'),
    array('id' => '685', 'prefecture_code' => '46', 'port_code' => '22', 'prefecture_name' => '鹿児島県', 'port_name' => '一湊'),
    array('id' => '686', 'prefecture_code' => '46', 'port_code' => '23', 'prefecture_name' => '鹿児島県', 'port_name' => '口永良部島'),
    array('id' => '687', 'prefecture_code' => '46', 'port_code' => '24', 'prefecture_name' => '鹿児島県', 'port_name' => '臥蛇島'),
    array('id' => '688', 'prefecture_code' => '46', 'port_code' => '25', 'prefecture_name' => '鹿児島県', 'port_name' => '中之島'),
    array('id' => '689', 'prefecture_code' => '46', 'port_code' => '26', 'prefecture_name' => '鹿児島県', 'port_name' => '宝島'),
    array('id' => '690', 'prefecture_code' => '46', 'port_code' => '27', 'prefecture_name' => '鹿児島県', 'port_name' => '笠利湾'),
    array('id' => '691', 'prefecture_code' => '46', 'port_code' => '28', 'prefecture_name' => '鹿児島県', 'port_name' => '名瀬'),
    array('id' => '692', 'prefecture_code' => '46', 'port_code' => '29', 'prefecture_name' => '鹿児島県', 'port_name' => '宇検'),
    array('id' => '693', 'prefecture_code' => '46', 'port_code' => '30', 'prefecture_name' => '鹿児島県', 'port_name' => '西古見湾'),
    array('id' => '694', 'prefecture_code' => '46', 'port_code' => '31', 'prefecture_name' => '鹿児島県', 'port_name' => '久慈湾'),
    array('id' => '695', 'prefecture_code' => '46', 'port_code' => '32', 'prefecture_name' => '鹿児島県', 'port_name' => '古仁屋'),
    array('id' => '696', 'prefecture_code' => '46', 'port_code' => '33', 'prefecture_name' => '鹿児島県', 'port_name' => '住用湾'),
    array('id' => '697', 'prefecture_code' => '46', 'port_code' => '34', 'prefecture_name' => '鹿児島県', 'port_name' => '請島'),
    array('id' => '698', 'prefecture_code' => '46', 'port_code' => '35', 'prefecture_name' => '鹿児島県', 'port_name' => '山村湾'),
    array('id' => '699', 'prefecture_code' => '46', 'port_code' => '36', 'prefecture_name' => '鹿児島県', 'port_name' => '和泊'),
    array('id' => '700', 'prefecture_code' => '46', 'port_code' => '37', 'prefecture_name' => '鹿児島県', 'port_name' => '茶花'),
    array('id' => '701', 'prefecture_code' => '46', 'port_code' => '38', 'prefecture_name' => '鹿児島県', 'port_name' => '波見'),
    array('id' => '702', 'prefecture_code' => '47', 'port_code' => '1', 'prefecture_name' => '沖縄県', 'port_name' => '我喜屋'),
    array('id' => '703', 'prefecture_code' => '47', 'port_code' => '2', 'prefecture_name' => '沖縄県', 'port_name' => '伊江'),
    array('id' => '704', 'prefecture_code' => '47', 'port_code' => '3', 'prefecture_name' => '沖縄県', 'port_name' => '運天'),
    array('id' => '705', 'prefecture_code' => '47', 'port_code' => '4', 'prefecture_name' => '沖縄県', 'port_name' => '渡久地'),
    array('id' => '706', 'prefecture_code' => '47', 'port_code' => '5', 'prefecture_name' => '沖縄県', 'port_name' => '那覇'),
    array('id' => '707', 'prefecture_code' => '47', 'port_code' => '6', 'prefecture_name' => '沖縄県', 'port_name' => '糸満'),
    array('id' => '708', 'prefecture_code' => '47', 'port_code' => '7', 'prefecture_name' => '沖縄県', 'port_name' => '石川'),
    array('id' => '709', 'prefecture_code' => '47', 'port_code' => '8', 'prefecture_name' => '沖縄県', 'port_name' => '馬天'),
    array('id' => '710', 'prefecture_code' => '47', 'port_code' => '9', 'prefecture_name' => '沖縄県', 'port_name' => '楚久'),
    array('id' => '711', 'prefecture_code' => '47', 'port_code' => '10', 'prefecture_name' => '沖縄県', 'port_name' => '座間味'),
    array('id' => '712', 'prefecture_code' => '47', 'port_code' => '11', 'prefecture_name' => '沖縄県', 'port_name' => '儀間'),
    array('id' => '713', 'prefecture_code' => '47', 'port_code' => '12', 'prefecture_name' => '沖縄県', 'port_name' => '南大東島'),
    array('id' => '714', 'prefecture_code' => '47', 'port_code' => '13', 'prefecture_name' => '沖縄県', 'port_name' => '平良'),
    array('id' => '715', 'prefecture_code' => '47', 'port_code' => '14', 'prefecture_name' => '沖縄県', 'port_name' => '長山'),
    array('id' => '716', 'prefecture_code' => '47', 'port_code' => '15', 'prefecture_name' => '沖縄県', 'port_name' => '石垣'),
    array('id' => '717', 'prefecture_code' => '47', 'port_code' => '16', 'prefecture_name' => '沖縄県', 'port_name' => '船浮'),
    array('id' => '718', 'prefecture_code' => '47', 'port_code' => '17', 'prefecture_name' => '沖縄県', 'port_name' => '比川'),
    array('id' => '719', 'prefecture_code' => '47', 'port_code' => '18', 'prefecture_name' => '沖縄県', 'port_name' => '黄尾嶼'),
    array('id' => '720', 'prefecture_code' => '47', 'port_code' => '19', 'prefecture_name' => '沖縄県', 'port_name' => '魚釣島'),
    array('id' => '721', 'prefecture_code' => '47', 'port_code' => '20', 'prefecture_name' => '沖縄県', 'port_name' => '白浜'),
    array('id' => '722', 'prefecture_code' => '47', 'port_code' => '21', 'prefecture_name' => '沖縄県', 'port_name' => '安田'),
    array('id' => '723', 'prefecture_code' => '47', 'port_code' => '22', 'prefecture_name' => '沖縄県', 'port_name' => '辺土名'),
    array('id' => '724', 'prefecture_code' => '47', 'port_code' => '23', 'prefecture_name' => '沖縄県', 'port_name' => '都屋'),
    array('id' => '725', 'prefecture_code' => '47', 'port_code' => '24', 'prefecture_name' => '沖縄県', 'port_name' => '平敷屋'),
    array('id' => '726', 'prefecture_code' => '47', 'port_code' => '25', 'prefecture_name' => '沖縄県', 'port_name' => '奥武島'),
    array('id' => '727', 'prefecture_code' => '47', 'port_code' => '26', 'prefecture_name' => '沖縄県', 'port_name' => '仲里'),
    array('id' => '728', 'prefecture_code' => '47', 'port_code' => '27', 'prefecture_name' => '沖縄県', 'port_name' => '池間'),
    array('id' => '729', 'prefecture_code' => '47', 'port_code' => '28', 'prefecture_name' => '沖縄県', 'port_name' => '佐良浜'),
    array('id' => '730', 'prefecture_code' => '47', 'port_code' => '29', 'prefecture_name' => '沖縄県', 'port_name' => '波照間'),
    array('id' => '731', 'prefecture_code' => '47', 'port_code' => '30', 'prefecture_name' => '沖縄県', 'port_name' => '久部良'),
    array('id' => '732', 'prefecture_code' => '47', 'port_code' => '31', 'prefecture_name' => '沖縄県', 'port_name' => '渡嘉敷'),
    array('id' => '733', 'prefecture_code' => '47', 'port_code' => '32', 'prefecture_name' => '沖縄県', 'port_name' => '泡瀬'),
    array('id' => '734', 'prefecture_code' => '47', 'port_code' => '33', 'prefecture_name' => '沖縄県', 'port_name' => '東'),
    array('id' => '735', 'prefecture_code' => '47', 'port_code' => '34', 'prefecture_name' => '沖縄県', 'port_name' => '宜名真'),
    array('id' => '736', 'prefecture_code' => '47', 'port_code' => '35', 'prefecture_name' => '沖縄県', 'port_name' => '兼城')
);

const MASTER_NAME = 'Sho Tsukamoto';
define("PLACES", $places);
define("ALL_PLACES", $all_places);